### ISSUE TITLE
Eletro magic tool dont show NEI recipes but work

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1000]
Many recipes are not visible with EMT 1.2.6.2

Nono and Quantum Boots
Nono and Quantum Helm(Googles)
Nano and Quantum Wings
Electric Hoe
All Tahumium tools and the higher versions of it.

I get the following error in the console:
``
[19:16:22] [Client thread/WARN] [IC2.Item/]: Detected invalid armor damage application:
java.lang.Throwable
	at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:154) [ItemArmorElectric.class:?]
	at net.minecraft.item.ItemStack.func_77964_b(Unknown Source) [add.class:?]
	at codechicken.nei.PositionedStack.setPermutationToRender(PositionedStack.java:99) [PositionedStack.class:?]
	at codechicken.nei.PositionedStack.<init>(PositionedStack.java:34) [PositionedStack.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.setIngredients(ShapedRecipeHandler.java:53) [ShapedRecipeHandler$CachedShapedRecipe.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:35) [ShapedRecipeHandler$CachedShapedRecipe.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler.forgeShapedRecipe(ShapedRecipeHandler.java:160) [ShapedRecipeHandler.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler.loadUsageRecipes(ShapedRecipeHandler.java:137) [ShapedRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:350) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:472) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20) [GuiUsageRecipe.class:?]
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20) [RecipeItemInputHandler.class:?]
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java) [bex.class:?]
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_72]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[19:16:22] [Client thread/ERROR] [NotEnoughItems/]: Error loading recipe: ``

**Comment by Dream-Master** [comment]
@Technus any idea what it can cause.

**Comment by Dream-Master** [comment]
Seems to be an Nei issue. So recipe shown in Thaumcraft Book and works in game.

**Comment by Dream-Master** [comment]
Nothing i can do jsut ignore.
