### ISSUE TITLE
Wrath Cage + Special Mob Crystal -> NPE spawm

### ISSUE THREAD

**Issue by Anikilulala** [GTNewHorizons/NewHorizons#1080]
While inserting crystal containing mob from Special Mob Mod, the console starts spawn log as follow:

```
Caused by: java.lang.NullPointerException
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.reflect.InvocationTargetException
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedConstructorAccessor214.newInstance(Unknown Source)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.entity.EntityList.func_75620_a(EntityList.java:122)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fox.spiteful.forbidden.tiles.WrathSpawnerLogic.getEntityForRender(WrathSpawnerLogic.java:289)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fox.spiteful.forbidden.client.TileEntityWrathCageRenderer.renderMob(TileEntityWrathCageRenderer.java:27)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fox.spiteful.forbidden.client.TileEntityWrathCageRenderer.renderTileEntityWrathCage(TileEntityWrathCageRenderer.java:22)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fox.spiteful.forbidden.client.TileEntityWrathCageRenderer.func_147500_a(TileEntityWrathCageRenderer.java:50)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147549_a(SourceFile:100)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mrtjp.relocation.ASMHacks$.renderTileEntityAt(hacks.scala:30)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at mrtjp.relocation.ASMHacks.renderTileEntityAt(hacks.scala)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_147544_a(SourceFile:92)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.ab.a(F:201)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.ak.a(F:475)
[19:01:18] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.HC.al(F:50)
```

The log file size increases at 1MB per second, and fills my harddisk to the full very soon.
This bug may be related to newly updata, because before I updata my game to the newest version, everything was alright(GTNH_1.2.1.0).

**Comment by Dream-Master** [comment]
Forbidden magic and project red had not been updated.
@Namikon , @Technus any idea.

**Comment by Dream-Master** [comment]
![image](https://user-images.githubusercontent.com/2970688/34320569-999eccd6-e7fd-11e7-94ac-ffa6676d1608.png)
![image](https://user-images.githubusercontent.com/2970688/34320572-a544fca4-e7fd-11e7-9b6d-34c17a51203e.png)
![image](https://user-images.githubusercontent.com/2970688/34320573-aaa93c96-e7fd-11e7-9cfb-76a11656bb6b.png)
![image](https://user-images.githubusercontent.com/2970688/34320575-b4fd5952-e7fd-11e7-8a4b-5315f52968e4.png)
No log spawming

**Comment by Dream-Master** [comment]
Maybe fixed
