### ISSUE TITLE
NPE at Thaumcraft-07-Aspect-Adds.zs:117

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#1210]
```
MineTweaker: Loading Thaumcraft-07-Aspect-Adds.zs
java.lang.NullPointerException
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getAspectsFromIngredients(ThaumcraftCraftingManager.java:861)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromCraftingRecipes(ThaumcraftCraftingManager.java:833)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTagsFromRecipes(ThaumcraftCraftingManager.java:903)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:551)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.generateTags(ThaumcraftCraftingManager.java:525)
	at thaumcraft.common.lib.crafting.ThaumcraftCraftingManager.getObjectTags(ThaumcraftCraftingManager.java:313)
	at thaumcraft.common.lib.InternalMethodHandler.getObjectAspects(InternalMethodHandler.java:46)
	at thaumcraft.api.ThaumcraftApiHelper.getObjectAspects(ThaumcraftApiHelper.java:95)
	at modtweaker2.mods.thaumcraft.handlers.Aspects$Add.apply(Aspects.java:51)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:176)
	at modtweaker2.mods.thaumcraft.handlers.Aspects.set(Aspects.java:31)
	at Thaumcraft-07-Aspect-Adds.__script__(Thaumcraft-07-Aspect-Adds.zs:117)
	at __ZenMain__.run(Thaumcraft-07-Aspect-Adds.zs)
```
This is just console warning, but perhaps part of `Thaumcraft-07-Aspect-Adds.zs` wont work.
Maybe errored because `getAspectsFromIngredients` can not get aspects from IC2 cell.

**Comment by Dream-Master** [comment]
Yeah seen this all ready but not sure why. Maybe have to using full or empty tanks  (meta or nbt data wrong )
