### ISSUE TITLE
Witchery Hand of Death / Adventure backpacks dupe bug

### ISSUE THREAD

**Issue by SirAzazel** [GTNewHorizons/NewHorizons#1229]
If you kill person with adventure backpack using Hand of Death (spamming) they can die multiple times (depends on how fast you can click person while death animation is playing) creating multiple OpenBlocks graves. Only first grave will have players items, but if player is wearing adventure backpack - backpack will be added to EVERY grave and will have all items that was on that backpack before death.

**Comment by Dream-Master** [comment]
@Ugachaga any idea here?

**Comment by SirAzazel** [comment]
Dream, hand of death doesnt do more than 0.5 heart of damage (so like hitting with hand), but it also has 1 heart worth of damage that ignores armor and any protection, probably this is dupe bug that exists for infinity sword too.

**Comment by Ugachaga** [comment]
https://github.com/runescapejon/AdventureBackpack2/releases/tag/Beta-0.9fb28

**Comment by Dream-Master** [comment]
@SirAzazel can you add the new Backpack version in your pack an test it please.

**Comment by Dream-Master** [comment]
@Ugachaga Thanks

**Comment by SirAzazel** [comment]
@Dream-Master @Ugachaga i am not able to recreate issue in SP with both b28pre1 and b27 (which is installed on GTNH) as it gives me error

`[15:47:50] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel witchery
java.lang.NullPointerException
	at cpw.mods.fml.common.network.FMLOutboundHandler$OutboundTarget$4.selectNetworks(FMLOutboundHandler.java:109) ~[FMLOutboundHandler$OutboundTarget$4.class:?]
	at cpw.mods.fml.common.network.FMLOutboundHandler.write(FMLOutboundHandler.java:273) ~[FMLOutboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:637) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:115) ~[MessageToMessageEncoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeWrite(DefaultChannelHandlerContext.java:644) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.write(DefaultChannelHandlerContext.java:698) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:688) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.writeAndFlush(DefaultChannelHandlerContext.java:717) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:893) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:239) ~[AbstractChannel.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:196) ~[SimpleNetworkWrapper.class:?]
	at com.emoniph.witchery.network.PacketPipeline.sendTo(PacketPipeline.java:51) ~[PacketPipeline.class:?]
	at com.emoniph.witchery.common.ExtendedPlayer.sync(ExtendedPlayer.java:878) ~[ExtendedPlayer.class:?]
	at com.emoniph.witchery.common.ExtendedPlayer.fillBloodReserve(ExtendedPlayer.java:548) ~[ExtendedPlayer.class:?]
	at com.emoniph.witchery.common.GenericEvents.onLivingDeath(GenericEvents.java:1799) ~[GenericEvents.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_187_GenericEvents_onLivingDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303) ~[ForgeHooks.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_70645_a(EntityPlayerMP.java:405) ~[mw.class:?]
	at com.emoniph.witchery.util.EntityUtil.touchOfDeath(EntityUtil.java:469) ~[EntityUtil.class:?]
	at com.emoniph.witchery.item.ItemDeathsHand.onLeftClickEntity(ItemDeathsHand.java:145) ~[ItemDeathsHand.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1190) ~[yz.class:?]
	at cofh.thermalexpansion.block.device.TileActivator.simLeftClick(TileActivator.java:359) ~[TileActivator.class:?]
	at cofh.thermalexpansion.block.device.TileActivator.doDeploy(TileActivator.java:188) ~[TileActivator.class:?]
	at cofh.thermalexpansion.block.device.TileActivator.func_145845_h(TileActivator.java:150) ~[TileActivator.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]`

Tested using Team CoFH mods (Autonomous activator) in SP. List of mods used in testing:

![](http://i.imgur.com/RtHCkaC.png)

**Comment by SirAzazel** [comment]
Forgot to mention: In SP with both versions of AdvBackpacks backpacks spawn on my feet pos and grave spawn over it, but on GTNH server it was spawning only grave containing backpack in it.

**Comment by Ugachaga** [comment]
I doubt this can be tested in SP. If you want backpack spawning into teh grave set `B:"Backpack Death Place"=false`

**Comment by Dream-Master** [comment]
@SirAzazel can you test it again and report here please?
Thanks
