### ISSUE TITLE
1.4.1.0pre GalaxySpace NPE and more

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#1256]
1.  Potion IDs from Randomthings [was changed](https://github.com/GTNewHorizons/NewHorizons/commit/6ef65f11e12e56f71e502a5575c6c9e968bad796#diff-39d82a853b730a6161f49446e631ec4aL56) for some reason. ID128 potentially unsafe.
2. Seems Baubles doesn't upgraded to newest version. Cannot test it, because:
3. My SP test world crushed.
```
java.lang.NullPointerException
	at galaxyspace.SolarSystem.core.handler.GSClientTickHandler.onClientTick(Unknown Source) ~[GSClientTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_669_GSClientTickHandler_onClientTick_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by Dream-Master** [comment]
OK thanks for testing will look into it when I am on a computer.

**Comment by Dream-Master** [comment]
Oh sorry i forgot Bauble to update will do that.

**Comment by Dream-Master** [comment]
Ok added to Pre2

**Comment by Dream-Master** [comment]
@Ugachaga Please try with my Pack i send to you the zip file linke and report it here back. Thanks.

**Comment by Dream-Master** [comment]
@Ugachaga I can join my Test Server and in sp all works fine too.

**Comment by Ugachaga** [comment]
Seems crash happening in certain point of my test world. This world is ugly mess of tons randomly placed items/multiblocks so i can't say what exactly causes crash. Something. Still happening in pre2.

**Comment by Dream-Master** [comment]
Maybe we should to report this to Galaxy space mod dev @Ugachaga

**Comment by Dream-Master** [comment]
ok i backdate to 1.1.3 and hope in 1.1.5 are not more bugs.

**Comment by Ugachaga** [comment]
Can confirm: successfully tested 1.4.1.0pre3

**Comment by Dream-Master** [comment]
Ok nice.
