### ISSUE TITLE
Fluid Solidifier Nei Texture Problem

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#1265]
![image](https://cloud.githubusercontent.com/assets/2970688/24452511/e91245ac-1483-11e7-9a42-ba94b9ef25bf.png)

@Technus any idea?

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24452545/14722cd0-1484-11e7-990e-eced17427fcf.png)
![image](https://cloud.githubusercontent.com/assets/2970688/24452549/1aef687a-1484-11e7-9b09-b060a0e9bc35.png)

Other Machines have this now too.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24452590/40f51cea-1484-11e7-8f0a-f22670ff22eb.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/24452605/4f7cdc08-1484-11e7-89f7-194b7f8db91d.png)

**Comment by Dream-Master** [comment]
```
 java.lang.ArrayIndexOutOfBoundsException
[B#349]  [13:33:31] [Client thread/WARN]: Failed to load texture: gregtech:textures/gui/basicmachines/Mixer.png
[B#349]  java.io.FileNotFoundException: gregtech:textures/gui/basicmachines/Mixer.png
[B#349]  	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(SourceFile:51) ~[bqq.class:?]
[B#349]  	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:67) ~[brg.class:?]
[B#349]  	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SourceFile:29) ~[bpu.class:?]
[B#349]  	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:89) [bqf.class:?]
[B#349]  	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:45) [bqf.class:?]
[B#349]  	at codechicken.lib.render.CCRenderState.changeTexture(CCRenderState.java:410) [CCRenderState.class:?]
[B#349]  	at codechicken.lib.render.CCRenderState.changeTexture(CCRenderState.java:406) [CCRenderState.class:?]
[B#349]  	at codechicken.lib.gui.GuiDraw.changeTexture(GuiDraw.java:121) [GuiDraw.class:?]
[B#349]  	at gregtech.nei.GT_NEI_DefaultHandler.drawBackground(GT_NEI_DefaultHandler.java:151) [GT_NEI_DefaultHandler.class:?]
[B#349]  	at codechicken.nei.recipe.GuiRecipe.func_146976_a(GuiRecipe.java:269) [GuiRecipe.class:?]
[B#349]  	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78) [bex.class:?]
[B#349]  	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061) [blt.class:?]
[B#349]  	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) [bao.class:?]
[B#349]  	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
[B#349]  	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
[B#349]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_72]
[B#349]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_72]
[B#349]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_72]
[B#349]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#349]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#349]  [13:33:54] [Client thread/ERROR] [NotEnoughItems]: Error loading recipe: 
[B#349]  java.lang.ArrayIndexOutOfBoundsException
```

**Comment by Dream-Master** [comment]
found the problem i guess.
