### ISSUE TITLE
multiple mining modes including 3x3 horizontal and vertical with Tic simple tools

### ISSUE THREAD

**Issue by CrusherX83** [GTNewHorizons/NewHorizons#1559]
So I just started a new 1.5 map and got my self a nice tinkers flint pickaxe. went to press ` for quest book and noticed a mining mode change. it allows my flint tools mine 3x3 area or larger for veins. it is caused by the keybind option     key.detrav.modeswitch
![2017-06-25_21 45 52](https://user-images.githubusercontent.com/29513029/27523294-e9918732-59f1-11e7-8318-2988cf57b95e.png)
![2017-06-25_21 48 03](https://user-images.githubusercontent.com/29513029/27523296-e993cf42-59f1-11e7-899b-2dc588b48dde.png)
![2017-06-25_21 48 29](https://user-images.githubusercontent.com/29513029/27523293-e9910708-59f1-11e7-8933-c1fa97a02b63.png)
![2017-06-25_22 00 24](https://user-images.githubusercontent.com/29513029/27523292-e990e2e6-59f1-11e7-8ea2-62bbd6b37b6e.png)
![2017-06-25_22 00 37](https://user-images.githubusercontent.com/29513029/27523295-e992a8f6-59f1-11e7-89a3-9591e035caad.png)

**Comment by mitchej123** [comment]
I saw this in the chat on discord and wanted to see what it did with the hammer, it worked with the pickaxe but when switching to my hammer it was only breaking 1 block.  Soon after I got disconnected on my client from my local server.

The server side blew up with about 100k lines of the following (before I force quit it):
```
[20:01:25] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$BreakEvent@3bdac35c:
java.lang.StackOverflowError
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_131]
        at java.lang.ClassLoader.checkPackageAccess(ClassLoader.java:500) ~[?:1.8.0_131]
        at cpw.mods.fml.common.eventhandler.EventBus.handleException(EventBus.java:154) ~[EventBus.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:145) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467) ~[ForgeHooks.class:?]
        at tconstruct.library.tools.HarvestTool.breakExtraBlock(HarvestTool.java:275) ~[HarvestTool.class:?]
        at tconstruct.library.tools.AOEHarvestTool.onBlockStartBreak(AOEHarvestTool.java:77) ~[AOEHarvestTool.class:?]
        at com.detrav.events.DetravBlockBreakEventHandler.tryHarvestBlock(DetravBlockBreakEventHandler.java:137) ~[DetravBlockBreakEventHandler.class:?]
        at com.detrav.events.DetravBlockBreakEventHandler.onBreakBlock(DetravBlockBreakEventHandler.java:104) ~[DetravBlockBreakEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1207_DetravBlockBreakEventHandler_onBreakBlock_BreakEvent.invoke(.dynamic) ~[?:?] 
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467) ~[ForgeHooks.class:?]
        at tconstruct.library.tools.HarvestTool.breakExtraBlock(HarvestTool.java:275) ~[HarvestTool.class:?]
        at tconstruct.library.tools.AOEHarvestTool.onBlockStartBreak(AOEHarvestTool.java:77) ~[AOEHarvestTool.class:?]
        at com.detrav.events.DetravBlockBreakEventHandler.tryHarvestBlock(DetravBlockBreakEventHandler.java:137) ~[DetravBlockBreakEventHandler.class:?]
        at com.detrav.events.DetravBlockBreakEventHandler.onBreakBlock(DetravBlockBreakEventHandler.java:104) ~[DetravBlockBreakEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1207_DetravBlockBreakEventHandler_onBreakBlock_BreakEvent.invoke(.dynamic) ~[?:?] 
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467) ~[ForgeHooks.class:?]
        at tconstruct.library.tools.HarvestTool.breakExtraBlock(HarvestTool.java:275) ~[HarvestTool.class:?]
        at tconstruct.library.tools.AOEHarvestTool.onBlockStartBreak(AOEHarvestTool.java:77) ~[AOEHarvestTool.class:?]
        at com.detrav.events.DetravBlockBreakEventHandler.tryHarvestBlock(DetravBlockBreakEventHandler.java:137) ~[DetravBlockBreakEventHandler.class:?]
        at com.detrav.events.DetravBlockBreakEventHandler.onBreakBlock(DetravBlockBreakEventHandler.java:104) ~[DetravBlockBreakEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_1207_DetravBlockBreakEventHandler_onBreakBlock_BreakEvent.invoke(.dynamic) ~[?:?] 
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467) ~[ForgeHooks.class:?]
        at tconstruct.library.tools.HarvestTool.breakExtraBlock(HarvestTool.java:275) ~[HarvestTool.class:?]
        at tconstruct.library.tools.AOEHarvestTool.onBlockStartBreak(AOEHarvestTool.java:77) ~[AOEHarvestTool.class:?]
        at com.detrav.events.DetravBlockBreakEventHandler.tryHarvestBlock(DetravBlockBreakEventHandler.java:137) ~[DetravBlockBreakEventHandler.class:?]
  {snip}
```

**Comment by bigbass1997** [comment]
This mod obviously adds a LOT more than just a scanner. Heracles even found this and pointed it out in Discord while trying to make the mod compatible with our version of GT.

Were all other features of the mod just ignored or not realized when it was decided to add it to the modpack?

**Comment by Dream-Master** [comment]
Yes was my first reaction when see the mod.
@bigbass1997 @CrusherX83 @mitchej123 
We have two options here 
1. Simone with more coding knowledge then me fix the wrong code. I fork the mod all ready and modifying it for the pack.
2. We kick the mod.

**Comment by Dream-Master** [comment]
Datrev Scanner mod will removed and only the scanners will be put back nothing more.

**Comment by Dream-Master** [comment]
GT Scanner mod is available at LuV.
