### ISSUE TITLE
Blast alloy smelter causing client crash/chunk corruption on completion.  (1.5.1.0)

### ISSUE THREAD

**Issue by NedStarCryo** [GTNewHorizons/NewHorizons#1834]
Version 1.5.1.0 ---- 05.08.2017

The crash happens in either singleplayer or multiplayer. When you try and build the blast alloy smelter and place the muffler hatch to complete the structure  the client will crash. 
Upon rejoining the client will crash again. It basically breaks the chunk. 

So far this is the only multi-structure I've had issues with, sadly its halting progression.

Very easy to reproduce as there's a 100% chance to have the issue occur. Tried it out on a new world with nothing there and it crashed instantly upon completion.

It throws the following error upon crash.

`[00:03:58] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at gregtech.api.metatileentity.implementations.GT_MetaTileEntity_Hatch.getTexture(GT_MetaTileEntity_Hatch.java:43) ~[GT_MetaTileEntity_Hatch.class:?]
	at gregtech.api.metatileentity.BaseMetaTileEntity.getTexture(BaseMetaTileEntity.java:1071) ~[BaseMetaTileEntity.class:?]
	at gregtech.common.render.GT_Renderer_Block.renderStandardBlock(GT_Renderer_Block.java:120) ~[GT_Renderer_Block.class:?]
	at gregtech.common.render.GT_Renderer_Block.renderWorldBlock(GT_Renderer_Block.java:588) ~[GT_Renderer_Block.class:?]
	at cpw.mods.fml.client.registry.RenderingRegistry.renderWorldBlock(RenderingRegistry.java:118) ~[RenderingRegistry.class:?]
	at FMLRenderAccessLibrary.renderWorldBlock(FMLRenderAccessLibrary.java:53) ~[FMLRenderAccessLibrary.class:?]
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:296) ~[blm.class:?]
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181) ~[blo.class:?]
	at fastcraft.ab.a(F:518) ~[fastcraft-1.23.jar:?]
	at fastcraft.ag.a(F:116) ~[fastcraft-1.23.jar:?]
	at fastcraft.HC.t(F:77) ~[fastcraft-1.23.jar:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187) ~[blt.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1011) ~[blt.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_141]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_141]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
`

Thanks in advance.

**Comment by Dream-Master** [comment]
I guess i know the source of the problem. Can you @NedStarCryo try it again when 1.5.1.1 is out?

**Comment by NedStarCryo** [comment]
Sure.
