### ISSUE TITLE
Gadomancy infusion claw causes crashes

### ISSUE THREAD

**Issue by benstuwie** [GTNewHorizons/NewHorizons#2196]
#### Which modpack version are you using?
2.0.1.3
#
#### If in multiplayer; On which server does this happen? 
Dirt huts
#
#### What did you try to do, and what did you expect to happen?
I used the gadomancy automation claw for thaumcraft infusions
#
#### What happend instead? (Attach screenshots if needed)
it crashed the server
https://pastebin.com/t05G0fzG
there's the server log
#
#### What do you suggest instead/what changes do you propose?
less crashes would be nice

**Comment by ko5h** [comment]
need info
claw work perfectly for me
at what stage is crash? which staff\wand do you use?

**Comment by alphaest** [comment]
I tried a gold capped silverwood wand and a void capped silverwood staff.
The crash happens the moment it is "clicking" the infusion matrix.
Crash happens no matter if infusion has a recipe or not.

Tick of the claw:
java.lang.NullPointerException: Ticking block entity
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
	at makeo.gadomancy.common.blocks.tiles.TileInfusionClaw.performClickBlock(TileInfusionClaw.java:250)
	at makeo.gadomancy.common.blocks.tiles.TileInfusionClaw.func_145845_h(TileInfusionClaw.java:102)
	at net.minecraft.world.World.func_72939_s(World.java:2580)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)

Crash inner exception:
Stacktrace:
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
	at makeo.gadomancy.common.blocks.tiles.TileInfusionClaw.performClickBlock(TileInfusionClaw.java:250)
	at makeo.gadomancy.common.blocks.tiles.TileInfusionClaw.func_145845_h(TileInfusionClaw.java:102)

-- Block entity being ticked --
Details:
	Name: TileInfusionClaw // makeo.gadomancy.common.blocks.tiles.TileInfusionClaw
	Block type: ID #2031 (tile.BlockInfusionClaw // makeo.gadomancy.common.blocks.BlockInfusionClaw)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-2612,73,43), Chunk: (at 12,4,11 in -164,2; contains blocks -2624,0,32 to -2609,255,47), Region: (-6,0; contains chunks -192,0 to -161,31, blocks -3072,0,0 to -2561,255,511)
	Actual block type: ID #2031 (tile.BlockInfusionClaw // makeo.gadomancy.common.blocks.BlockInfusionClaw)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2580)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)

**Comment by alphaest** [comment]
Also this isn't a constant thing.
If you set the infusion on a timer and let the server crash, it will boot up and work fine. Even if you remove the staff between and recharge it and put it back.

**Comment by Dream-Master** [comment]
@HellFirePvP any idea about this ?

**Comment by Dream-Master** [comment]
Not get an aswer sadly.

**Comment by Lithorn** [comment]
Do not have log access but, a user placed the claw on their alter and a redstone clock and the server crashes on loadup whenever they log in.

**Comment by Fapiko** [comment]
Have you tested this on 2.0.1.5? I have a bunch of infusion claws setup and it works fine

**Comment by bartimaeusnek** [comment]
should be fixed (in testing now)
