### ISSUE TITLE
Crash caused by incorrect chest generation

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/NewHorizons#2203]
#### Which modpack version are you using?
2.0.1.3
#
#### What did you try to do, and what did you expect to happen?
Testing worldgen
#
#### What happend instead? (Attach screenshots if needed)
Minecraft crashes during chest generation
04:32:03] [Client thread/INFO]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11/20/17 4:32 AM
Description: Ticking memory connection

java.lang.IllegalArgumentException: bound must be positive
at java.util.Random.nextInt(Random.java:388)
at net.minecraftforge.common.ChestGenHooks.generateStacks(ChestGenHooks.java:111)
at net.minecraft.util.WeightedRandomChestContent.generateChestContent(WeightedRandomChestContent.java:93)
at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:38)
at net.minecraft.world.gen.structure.StructureComponent.func_74879_a(StructureComponent.java:744)
at net.minecraft.world.gen.structure.StructureVillagePieces$House2.func_74875_a(StructureVillagePieces.java:934)
at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
at rwg.world.ChunkGeneratorRealistic.func_73153_a(ChunkGeneratorRealistic.java:496)
at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
at net.minecraft.server.management.PlayerManager$PlayerInstance.(PlayerManager.java:370)
at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:174)
at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267)
at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313)
at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404)
at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

Happens with world seed = -1, travel due south ~1500 blocks, should hit it.
#
#### What do you suggest instead/what changes do you propose?

I think I found the culprit.

https://github.com/GTNewHorizons/NewHorizons/blob/master/config/TooMuchLoot/loot/villageBlacksmith.xml#L119
```
<loot item="TConstruct:shovel" damage="0" nbt="{InfiTool:{BaseDurability:356,Head:14,BaseAttack:5,ToolEXP:0L,Built:1b,HarvestLevel:4,Attack:5,RenderHead:14,ModDurability:0.0f,Handle:14,Broken:0b,Shoddy:0.0f,RenderHandle:14,MiningSpeed:650,ToolLevel:1,Unbreaking:1,Damage:0,BonusDurability:0,TotalDurability:356,Modifiers:0},display:{Name:&quot;§fBronze Shovel&quot;}}" weight="1" count_min="10" count_max="1"/>
```
Notice count_min is greater than count_max. Bad mod, it should be giving you an error message or defaulting to safe numbers instead of passing on a crashing setting!

**Comment by richardhendricks** [comment]
Probably supposed to be weight=10, based on other two entries next to it.

**Comment by Dream-Master** [comment]
Ok Need to fix it
