### ISSUE TITLE
BUG with molten Cell and Plasma Cells

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#2245]
When i load the newest Beta Pack 2.0.2.0 GTNH i get every start this window:

GT 5.09.32.11
Core Mod 1.5.13
GT++ 1.6.99 lastest source

https://media.discordapp.net/attachments/175668782327398401/388380167820541953/unknown.png?width=1202&height=677

Full fml log
https://gist.github.com/Dream-Master/24c440d8890f34d262e183b3b852ea45#file-log

Look at this error:
```

[21:01:46] [Client thread/WARN] [FML/]: ****************************************
[21:01:46] [Client thread/WARN] [FML/]: * The object gtPlusPlus.core.item.base.cell.BaseItemCell@49c74232 (name miscutils:itemCellSoulSand) is being added too late.
[21:01:46] [Client thread/WARN] [FML/]: *  at cpw.mods.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:399)
[21:01:46] [Client thread/WARN] [FML/]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:849)
[21:01:46] [Client thread/WARN] [FML/]: *  at cpw.mods.fml.common.registry.GameData.registerItem(GameData.java:812)
[21:01:46] [Client thread/WARN] [FML/]: *  at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:149)
[21:01:46] [Client thread/WARN] [FML/]: *  at cpw.mods.fml.common.registry.GameRegistry.registerItem(GameRegistry.java:137)
[21:01:46] [Client thread/WARN] [FML/]: *  at gtPlusPlus.core.item.base.BaseItemComponent.<init>(BaseItemComponent.java:41)...
[21:01:46] [Client thread/WARN] [FML/]: ****************************************
[21:01:46] [Client thread/INFO] [GT++/]: Generating a SoulSand Plasma Cell
[21:01:46] [Client thread/WARN] [FML/]: ****************************************

```
If you click on this cells(ic2 cells) the game crash

https://gist.github.com/Dream-Master/402b7c7094838dbc9bc05d2c3d77fe90#file-crash

First though was GT++ . I try my for of Gt++ and GT++ original version by @draknyte1 and get the same issue.

I guess somethings in us GTNH GT fork or Core Mod fore are wrong or different.

So long this issue is not fixed i am not able to update to 2.0.2.0

So i need help here:

@Technus 
@richardhendricks

**Comment by LOKKO12** [comment]
Possible workaround outcomment the gtPlusPlus.core.item.base.cell.BaseItemCell for soulsand, maybe?

**Comment by Dream-Master** [comment]
How?

**Comment by LOKKO12** [comment]
to outcomment Line 9 in GT++/core/material/nonmaterial.java, maybe that helps, but im not a pro =)

**Comment by Dream-Master** [comment]
No this not helped here. Need to digg deeper.

**Comment by Dream-Master** [comment]
With gt++ 1.6.07 i not get any issue

After i remove the Ore find mod IWF0.9 and backdate avaritia to the old version 1.14 i get only nei errors and a spawming console but no crash when open up molten glowstone or the plasma cell glowstone.

![image](https://user-images.githubusercontent.com/2970688/33788048-5426205c-dc70-11e7-9795-3dcab9db5844.png)

**Comment by Dream-Master** [comment]
And log still exists that cells are loaded too late
