### ISSUE TITLE
Bugged recipe

### ISSUE THREAD

**Issue by noobyaran9** [GTNewHorizons/NewHorizons#2403]
#### Which modpack version are you using?
2.0.2.5
#
#### If in multiplayer; On which server does this happen? 
Delta and only delta. IDK about epsi
#
#### What did you try to do, and what did you expect to happen?
Crafting quantum link chamber.
#
#### What happend instead? (Attach screenshots if needed)
This recipe:
![2018-01-13_02 08 53](https://user-images.githubusercontent.com/13598309/34889436-ee997324-f808-11e7-9ac2-81fb02b1000f.png)

It just kicks people out of the server. It also ate the material and doesn't give any results.
#
#### What do you suggest instead/what changes do you propose?
Not sure whats wrong.

**Comment by Dream-Master** [comment]
I need to see the logs on the server and the client to be sure what it is @noobyaran9

**Comment by LOKKO12** [comment]
> found another error
```
[02:03:27] [NEI Item Filtering/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@7983ea42:
java.lang.NullPointerException
    at squeek.spiceoflife.foodtracker.FoodHistory.get(FoodHistory.java:224) ~[FoodHistory.class:?]
    at squeek.spiceoflife.gui.TooltipHandler.onItemTooltip(TooltipHandler.java:89) ~[TooltipHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1499_TooltipHandler_onItemTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) [ForgeEventFactory.class:?]
    at net.minecraft.item.ItemStack.func_82840_a(Unknown Source) [add.class:?]
    at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:119) [GuiContainerManager.class:?]
    at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:162) [GuiContainerManager.class:?]
    at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:529) [ItemInfo.class:?]
    at codechicken.nei.ItemList$PatternItemFilter.matches(ItemList.java:65) [ItemList$PatternItemFilter.class:?]
    at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:110) [ItemList$AnyMultiItemFilter.class:?]
    at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:85) [ItemList$AllMultiItemFilter.class:?]
    at codechicken.nei.ItemList$2.execute(ItemList.java:239) [ItemList$2.class:?]
    at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
```

> this error spammed like 5~6 times
> after i craft smth using the terminal
> another thing i found
> it only kick me out when i try to craft the me quantum link chamber

is what he said to me before going offline

**Comment by Dream-Master** [comment]
Its the food history say in this error in combination with nei.

**Comment by LOKKO12** [comment]
```
[01:29:57] [NEI Item Filtering/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@22a782b4:
java.lang.IllegalStateException: Keyboard must be created before you can query key state
    at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:406) ~[lwjgl-2.9.1.jar:?]
    at minetweaker.mc1710.ForgeEventHandler.onItemTooltip(ForgeEventHandler.java:43) ~[ForgeEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_619_ForgeEventHandler_onItemTooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) [ForgeEventFactory.class:?]
    at net.minecraft.item.ItemStack.func_82840_a(Unknown Source) [add.class:?]
    at codechicken.nei.guihook.GuiContainerManager.itemDisplayNameMultiline(GuiContainerManager.java:119) [GuiContainerManager.class:?]
    at codechicken.nei.guihook.GuiContainerManager.concatenatedDisplayName(GuiContainerManager.java:162) [GuiContainerManager.class:?]
    at codechicken.nei.api.ItemInfo.getSearchName(ItemInfo.java:529) [ItemInfo.class:?]
    at codechicken.nei.ItemList$PatternItemFilter.matches(ItemList.java:65) [ItemList$PatternItemFilter.class:?]
    at codechicken.nei.ItemList$AnyMultiItemFilter.matches(ItemList.java:110) [ItemList$AnyMultiItemFilter.class:?]
    at codechicken.nei.ItemList$AllMultiItemFilter.matches(ItemList.java:85) [ItemList$AllMultiItemFilter.class:?]
    at codechicken.nei.ItemList$2.execute(ItemList.java:239) [ItemList$2.class:?]
    at codechicken.nei.RestartableTask$1.run(RestartableTask.java:24) [RestartableTask$1.class:?]
```
>This error happens when i open AE terminal

**Comment by noobyaran9** [comment]
Just tried to recreate the issue on server and it's not happening anymore. However, yesterday when I try to craft it, it doesn't give me the achievements and kick me out of server. I have a strong feeling that it is related to achievement.

**Comment by Dream-Master** [comment]
Maybe

**Comment by noobyaran9** [comment]
Possibly related to this 
#https://github.com/GTNewHorizons/NewHorizons/issues/2402

**Comment by Dream-Master** [comment]
Not fully fixed but not crash anymore.
Thanks @LOKKO12
