### ISSUE TITLE
Server Down becuase out of Memory?

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#244]
Why is the server down. No body on today?

**Comment by Teteros** [comment]
No idea, I thought it was off for updates.
Does it go down without activity?

**Comment by Dream-Master** [comment]
````````````````````````````````````````````````````````````````````````````````
[14:15:41] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save DreamCraft
[14:19:42] [PR RoutingThread #0/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.OutOfMemoryError: Java heap space
[14:19:42] [PR RoutingThread #0/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.Router.refreshRoutingTable(router.scala:327)
[14:19:42] [PR RoutingThread #0/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.RouteLayerUpdater.run(routingthread.scala:74)
[14:21:21] [PR RoutingThread #0/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.TableUpdateThread.run(routingthread.scala:40)
[14:22:26] [PR RoutingThread #1/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.OutOfMemoryError: Java heap space
[14:25:46] [PR RoutingThread #1/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.Router.refreshRoutingTable(router.scala:327)
[14:29:29] [PR RoutingThread #1/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.RouteLayerUpdater.run(routingthread.scala:74)
[14:33:18] [PR RoutingThread #1/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.TableUpdateThread.run(routingthread.scala:40)
[14:38:11] [PR RoutingThread #2/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.OutOfMemoryError: Java heap space
[15:01:32] [PR RoutingThread #2/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.Router.refreshRoutingTable(router.scala:366)
[15:05:50] [PR RoutingThread #2/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.RouteLayerUpdater.run(routingthread.scala:74)
[15:16:17] [PR RoutingThread #2/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at mrtjp.projectred.transportation.TableUpdateThread.run(routingthread.scala:40)
[15:38:56] [Snooper Timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.OutOfMemoryError: Java heap space
[15:43:07] [Snooper Timer/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.io.BufferedWriter.<init>(BufferedWriter.java:105)
[15:49:50] [File IO Thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.OutOfMemoryError: Java heap space
[15:50:49] [PR RoutingThread #3/INFO] [STDERR/ProjRed|Transportation]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.OutOfMemoryError: Java heap space
[15:59:02] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save DreamCraft
[16:18:01] [Server console handler/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.OutOfMemoryError: Java heap space
[16:19:58] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save DreamCraft
[16:31:25] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save DreamCraft
[16:39:05] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save DreamCraft
[16:45:34] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save DreamCraft
[16:51:46] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save DreamCraft
[17:01:42] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save DreamCraft

````````````````````````````````````````````````````````````````````
