### ISSUE TITLE
Server crash when breaking or placing gregtech pipes/cables/machines.

### ISSUE THREAD

**Issue by NedStarCryo** [GTNewHorizons/NewHorizons#2510]
**On 2.0.2.7**

Sometimes when placing a gregtech cable/pipe or when wrenching a gregtech machine the server instantly crashes. I've had the exact same issue a few months back when I was playing an older version of this modpack. The issue doesn't seem to exist at first but the more machines/pipes are placed in the world the more frequent it becomes. I've reached a point where I crash the server every  so few minutes when placing cables/pipes.

The server itself never crashes beyond the above mentioned actions. Every other mod runs fine except when you start messing around with gregtech do I run the risk of crashing my server.

#
#### If in multiplayer; On which server does this happen? 

Unsure if MP only. It's happening on my own server which is using a:

3570k
16 gigs of ram, of which 12 I dedicated to the MC server.
MC server is running on an SSD.
jre1.8.0_161 (64 bit)
There are some "can't keep up! Did the system time change warnings" but afaik those are unavoidable?

server crash log:
[crash-2018-01-24_15.04.53-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1660115/crash-2018-01-24_15.04.53-server.txt)
[crash-2018-01-24_13.08.27-server.txt](https://github.com/GTNewHorizons/NewHorizons/files/1660116/crash-2018-01-24_13.08.27-server.txt)
[2018-01-24-7.log](https://github.com/GTNewHorizons/NewHorizons/files/1660189/2018-01-24-7.log)

> [15:26:35] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world entities
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_161]
	at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.world.World.func_72939_s(World.java:1933) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 

> more
Description: Exception in server tick loop
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.entity.EntityTracker.func_72788_a(EntityTracker.java:269)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:648)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

I would very much appreciate some potential insight in this issue.

**Comment by Dream-Master** [comment]
wireless redstone bug i see in one log.

**Comment by NedStarCryo** [comment]
In the 2nd log indeed, weird seeing as we don't use anything from wireless redstone atm.
Regarding the first one, which is the error I'm getting most of the time. Any info can be gained from that one?

I did a bit of googling but it mostly seemed to be an error with no real way to find out what's causing it.

Sadly the crashes are entirely random but always related to placing  gregtech cables/pipes. 
Seeing as this isn't the first time I end up getting this error, despite a whole new world. Has nobody else ever had server crashes while laying gregtech pipes or placing gregtech cables?

**Comment by richardhendricks** [comment]
Hmm.  I don't think we've seen other issues with the placements causing crashes.  Can you try watching what you are doing and describe it in detail?

IE, placing cable/pipe on non-GT block, or on GT block, connecting a pipe to another pipe after placement using a wrench, breaking a pipe and it coming into your inventory, holding shift while placing, crossing a chunk while placing, etc.  Try turning on chunk boundaries with F9 twice and see if there is a correlation there.

The first error lacks any detailed info on what is causing the crash, but maybe some action that you do unconsciously is causing the error or making it more likely to occur.  What would be great would be a video so we can follow along and duplicate exactly.

My WAG as to what is happening is that it looks like something is removing itself from a list, while Java is trying to iterate across the list.  Guessing, but maybe an item is removing itself from the list of entities?  Not sure why it would effect you more than anyone else though.

Maybe try running the server for testing on a different PC and see if the problems continue?

**Comment by richardhendricks** [comment]
https://www.journaldev.com/378/java-util-concurrentmodificationexception

**Comment by NedStarCryo** [comment]
Thanks a lot for the information. I'll be doing some more debugging on my end and will definitely try and run it on another pc to see if that fixes the issue.
It seems to have been alright tonight after deleting a bunch of pipes in a chunk that somehow "lost their connection" 

http://www.theicecave.net/files/user/pictures/screencaps/javaw_2018-01-24_18-38-18.jpg

I'll be looking into it further, once again many thanks.

**Comment by Dream-Master** [comment]
@NedStarCryo open it if you need.
