### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Beladric** [GTNewHorizons/NewHorizons#2677]
Hey everyone !! i need your help,

#### Which modpack version are you using?

We use 2.0.2.7

#### If in multiplayer; On which server does this happen? 

This happen in personal server.

#### What did you try to do, and what did you expect to happen?

We have try to breed crops.

#### What happend instead? (Attach screenshots if needed)

Server crashed, and when we try to restart it he crash again.

[11:28:08] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at lokko12.berriespp.crops.BoP.WildCarrotsCrop.attributes(WildCarrotsCrop.java:38) ~[WildCarrotsCrop.class:?]
	at ic2.core.crop.TileEntityCrop.calculateRatioFor(TileEntityCrop.java:415) ~[TileEntityCrop.class:?]
	at ic2.core.crop.TileEntityCrop.attemptCrossing(TileEntityCrop.java:311) ~[TileEntityCrop.class:?]
	at ic2.core.crop.TileEntityCrop.tick(TileEntityCrop.java:174) ~[TileEntityCrop.class:?]
	at ic2.core.crop.TileEntityCrop.func_145845_h(TileEntityCrop.java:122) ~[TileEntityCrop.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more
[11:28:08] [Server thread/ERROR]: This crash report has been saved to: C:\Users\kilia\Desktop\Serveur\.\crash-reports\crash-2018-03-10_11.28.08-server.txt

I hope that you can help us because we can not play anymore.

**Comment by Beladric** [comment]
We have delete crop with mc edit and the server works again, so the problem come from crops, if someone have solution to fix our problem he is welcome. :)

**Comment by Dream-Master** [comment]
fixed in 2.0.3.0
