### ISSUE TITLE
Client Crash - Potentially SuperTic related

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/NewHorizons#2687]
#### Which modpack version are you using?
2.0.3.0

# 
#### If in multiplayer; On which server does this happen? 
Locally hosted server & client.

#
#### What did you try to do, and what did you expect to happen?
Sorting through my inventory and dumping into chests the client crashed.

#
#### What happend instead? (Attach screenshots if needed)
Client crash, looks potentially SuperTic related - Issue reported on mod github - https://github.com/Zoko061602/Super-TiC/issues/1

#
#### What do you suggest instead/what changes do you propose?

Look into/fix crash, or at least the console spam.

**Comment by Kortako** [comment]
I just want to point out that I've had the exact same issue for a few months every once in a while with the Spice of Life mod.  I open a chest and try to dump things in, my client freezes and then closes, and the log will have a concurrent modification exception.  It seems to be a general issue that pops up when you're shift clicking things really fast into a chest and it's trying to render tooltips too.  Mods that modify/add info to those tooltips seem to be the problem in my experience.  It's mildly annoying because it only happens every once in a while.

**Comment by Zoko061602** [comment]
I added some non-null checks, that might fixed it, but I'm not sure, since every time I tested this mod, I had no problems.

**Comment by bartimaeusnek** [comment]
this is related to potions that arent registered propperly. @Kortako @Zoko061602 see #2633 and #883

**Comment by Zoko061602** [comment]
@bartimaeusnek  are you sure? I thought that the event Itemstack might be null

**Comment by mitchej123** [comment]
I tried with your fix, and added a few new safeguards, still similar error spamming the log.  It's consistently the Config.eff.get() that's throwing the error.

**Comment by Zoko061602** [comment]
@mitchej123 line 37 ?

**Comment by mitchej123** [comment]
Yes.  This time I noticed it was throwing the error before even fully logged in.
```java
37:		          Integer materialId = ((IToolPart)item).getMaterialID(e.itemStack);
38:		          if(materialId <= 0 ) return;
39:			    id = Config.eff.get(materialId);		       			 
```

```
[13:04:19] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.ItemTooltipEvent@2321e238:
java.lang.NullPointerException
	at com.Zoko061602.SuperTic.TooltipEventHandler.addPartTooltips(TooltipEventHandler.java:39) ~[TooltipEventHandler.class:?]
	at com.Zoko061602.SuperTic.TooltipEventHandler.addTooltips(TooltipEventHandler.java:25) ~[TooltipEventHandler.class:?]
	at com.Zoko061602.SuperTic.SuperEventHandler.Tooltip(SuperEventHandler.java:16) ~[SuperEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_873_SuperEventHandler_Tooltip_ItemTooltipEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:169) [ForgeEventFactory.class:?]
	at net.minecraft.item.ItemStack.func_82840_a(Unknown Source) [add.class:?]
	at stevesaddons.threading.SearchItems.setItems(SearchItems.java:82) [SearchItems.class:?]
	at stevesaddons.network.message.SearchRegistryGenerateMessage.onMessage(SearchRegistryGenerateMessage.java:29) [SearchRegistryGenerateMessage.class:?]
	at stevesaddons.network.message.SearchRegistryGenerateMessage.onMessage(SearchRegistryGenerateMessage.java:11) [SearchRegistryGenerateMessage.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) [SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) [SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_161]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Zoko061602** [comment]
I updated the mod to 1.1.1
I'm not sure if it works (I can't reproduce this issue), but if every value in Config.eff is set to 1 , there shouldn't be a Nullpointer Exception.

**Comment by Dream-Master** [comment]
@Zoko061602 new crash log with version 1.1.1

https://gist.github.com/Dream-Master/73f841a36f279214e80f8ee89e4ce6fc

**Comment by Dream-Master** [comment]
1.1 start the game

**Comment by Kortako** [comment]
Is there any progress with this?  I just realized that it's not just crashing the game (I haven't experience a crash yet, personally), but it's spamming my log every time I mouse over something and it has to draw a tooltip.  That happens a LOT while I'm playing, and since I play with the console open, after a while MultiMC just crashes because it can't handle the log a 500-700mb log file.  I'd really like to get that console spam fixed if I could.

**Comment by Dream-Master** [comment]
@Zoko061602 we need your help here or I am forced to take the mod out in 2.0.3.1 so long we get a fix.

**Comment by Kortako** [comment]
Update on this actually: I just tried version 1.1.1a from CurseForge and that seems to work on the server and fix the console spam I was getting.

**Comment by Dream-Master** [comment]
Ah ok. Thanks for Info
