### ISSUE TITLE
OpenComputers warning message on every game load / login

### ISSUE THREAD

**Issue by Kortako** [GTNewHorizons/NewHorizons#2692]
#### Which modpack version are you using?
2.0.3.0
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happend instead? (Attach screenshots if needed)
Every time you load in, it comes up with this message:
![oc](https://user-images.githubusercontent.com/5300243/37271067-9e3c9862-258e-11e8-9655-1762b1947819.png)
#
#### What do you suggest instead/what changes do you propose?
There seems to be a bug with one of the recipes.  Looking at the log shows this error at load time:

> [00:28:15] [Client thread/INFO] [OpenComputers/OpenComputers]: Initializing recipes.
[00:28:15] [Client thread/WARN] [OpenComputers/OpenComputers]: No recipe for 'gemDiamond', you will not be able to craft this item. To suppress this warning, disable the recipe (assign `false` to it).
[00:28:15] [Client thread/WARN] [OpenComputers/OpenComputers]: Failed parsing loot disk recipes.
com.typesafe.config.ConfigException$WrongType: Reader: 48: lootDisks has type BOOLEAN rather than LIST
	at com.typesafe.config.impl.SimpleConfig.findKey(SimpleConfig.java:133) ~[SimpleConfig.class:?]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:145) ~[SimpleConfig.class:?]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:159) ~[SimpleConfig.class:?]
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:164) ~[SimpleConfig.class:?]
	at com.typesafe.config.impl.SimpleConfig.getList(SimpleConfig.java:212) ~[SimpleConfig.class:?]
	at com.typesafe.config.impl.SimpleConfig.getHomogeneousWrappedList(SimpleConfig.java:336) ~[SimpleConfig.class:?]
	at com.typesafe.config.impl.SimpleConfig.getObjectList(SimpleConfig.java:354) ~[SimpleConfig.class:?]
	at com.typesafe.config.impl.SimpleConfig.getConfigList(SimpleConfig.java:359) ~[SimpleConfig.class:?]
	at li.cil.oc.common.recipe.Recipes$.init(Recipes.scala:160) [Recipes$.class:?]
	at li.cil.oc.common.Proxy.init(Proxy.scala:92) [Proxy.class:?]
	at li.cil.oc.client.Proxy.init(Proxy.scala:47) [Proxy.class:?]
	at li.cil.oc.OpenComputers$.init(OpenComputers.scala:43) [OpenComputers$.class:?]
	at li.cil.oc.OpenComputers.init(OpenComputers.scala) [OpenComputers.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532) [FMLModContainer.class:?]
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212) [LoadController.class:?]
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190) [LoadController.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) [guava-17.0.jar:?]
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) [guava-17.0.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:275) [guava-17.0.jar:?]
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119) [LoadController.class:?]
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737) [Loader.class:?]
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

**Comment by Dream-Master** [comment]
Yea sean that too. Recipes works all fine but maybe some config file corrupted.
