### ISSUE TITLE
Osmotic Enchanter Crash

### ISSUE THREAD

**Issue by Mc-Flausch** [GTNewHorizons/NewHorizons#2764]
#### Which modpack version are you using?
2.0.3.0 but happened in 2.0.2.7 too
#
#### If in multiplayer; On which server does this happen? 
Single Player
#
#### What did you try to do, and what did you expect to happen?
Enchanting Boots of the Traveler.
Get enchanted Boots.
#
#### What happend instead? (Attach screenshots if needed)
The game crashed on every attempt.
For screenshots/ crashlogs I'd like  to refer to my forum post:
[Original Post](http://www.gtnewhorizons.com/forum/m/36844562/viewthread/31787467-bug-report-osmotic-enchanter)
#
#### What do you suggest instead/what changes do you propose?
Today I tried the Thaumic Tinker version Infinity Evolved v2.6.0 uses ( ThaumicTinkerer-2.5-1.7.10-512 ) and it worked perfectly fine ( 3 enchants with scepter swaping and one relog inbetween). 
There were however no essentia particles moving from the pillars to the [enchanter](https://imgur.com/a/2vcFt) Those I guess were causing my client to crash. 
Since I personally don't like the essentia trail that much anyway, would it be possible to add a config option to disable it?

With this modpack using a supposedly modified TT mod file, I'm not sure about reporting this crash to them.

**Comment by bartimaeusnek** [comment]
as it seems some ASM is fucking with the particles here:
```

	at cpw.mods.fml.common.eventhandler.ASMEventHandler_231_ParticleEngine_updateParticles_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)

```
will see what i can do here.

**Comment by draknyte1** [comment]
> as it seems some ASM is fucking with the particles here:

That's just how forge hooks events, totally unrelated to this issue from what that snippet shows.

**Comment by bartimaeusnek** [comment]
please try this version:
https://github.com/bartimaeusnek/ThaumicTinkerer/releases/download/2.5-554-GTNH/ThaumicTinkerer-1.7.10.2.5-1.7.10.jar

**Comment by Mc-Flausch** [comment]
Gave this one a try, so far it seems to work perfectly fine.
Did enchant a few boots in my regular world, with taking the scepter out couple of times( to mess with the particle stream), relog during enchant. Also gave it a try in a test world with a sword and every enchant I could possibly put on it. Again with scepter swapping during enchantment, relog during the process, restart the whole game, not a single crash.
Thank you
