### ISSUE TITLE
spaw lag

### ISSUE THREAD

**Issue by lexx1191** [GTNewHorizons/NewHorizons#2780]
#### Which modpack version are you using?

# 2.0.3.0
#### If in multiplayer; On which server does this happen? 

#single
#### What did you try to do, and what did you expect to happen?

#spam lag with different coordinates
[19:20:10] [Client thread/WARN]: An error occoured while processing onPlayerUsesItem. Please report
[19:20:10] [Client thread/ERROR]: [Ljava.lang.StackTraceElement;@292f7534
[19:20:10] [Client thread/INFO]: InvTweaks: net.minecraft.client.gui.GuiTextField
[19:20:10] [Client thread/INFO]: InvTweaks: successfully transformed setFocused/func_146195_b
[19:20:14] [Server thread/INFO]: [gregtech.api.metatileentity.BaseMetaTileEntity:func_145845_h:580]: WARNING: Possible Lag Source at [310, 51, -328] in Dimension 0 with 139ms caused by an instance of class gregtech.common.tileentities.automation.GT_MetaTileEntity_SuperBuffer
[19:20:15] [Server thread/WARN]: WARNING: Possible Lag Source at [299,63,-200] in Dimension 0 with 103 ms caused by an instance of class gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Fluid
[19:20:38] [Server thread/INFO]: [gregtech.api.metatileentity.BaseMetaTileEntity:func_145845_h:580]: WARNING: Possible Lag Source at [265, 54, -196] in Dimension 0 with 152ms caused by an instance of class gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine_GT_Recipe
[19:20:55] [Server thread/INFO]: Transforming Class (appeng.crafting.CraftingTreeProcess)

#
[latest.log](https://github.com/GTNewHorizons/NewHorizons/files/1872259/latest.log)
repeats the same way lag

[19:23:29] [Client thread/WARN]: Detected invalid armor damage application:
java.lang.Throwable
	at ic2.core.item.armor.ItemArmorElectric.setDamage(ItemArmorElectric.java:154) [ItemArmorElectric.class:?]
	at net.minecraft.item.ItemStack.func_77964_b(Unknown Source) [add.class:?]
	at codechicken.nei.PositionedStack.setPermutationToRender(PositionedStack.java:99) [PositionedStack.class:?]
	at codechicken.nei.PositionedStack.<init>(PositionedStack.java:34) [PositionedStack.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.setIngredients(ShapedRecipeHandler.java:53) [ShapedRecipeHandler$CachedShapedRecipe.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler$CachedShapedRecipe.<init>(ShapedRecipeHandler.java:35) [ShapedRecipeHandler$CachedShapedRecipe.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler.forgeShapedRecipe(ShapedRecipeHandler.java:160) [ShapedRecipeHandler.class:?]
	at codechicken.nei.recipe.ShapedRecipeHandler.loadUsageRecipes(ShapedRecipeHandler.java:137) [ShapedRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.loadUsageRecipes(TemplateRecipeHandler.java:350) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.TemplateRecipeHandler.getUsageHandler(TemplateRecipeHandler.java:472) [TemplateRecipeHandler.class:?]
	at codechicken.nei.recipe.GuiUsageRecipe.openRecipeGui(GuiUsageRecipe.java:20) [GuiUsageRecipe.class:?]
	at codechicken.nei.recipe.RecipeItemInputHandler.lastKeyTyped(RecipeItemInputHandler.java:20) [RecipeItemInputHandler.class:?]
	at codechicken.nei.guihook.GuiContainerManager.lastKeyTyped(GuiContainerManager.java:307) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73869_a(GuiContainer.java) [bex.class:?]
	at appeng.client.gui.implementations.GuiMEMonitorable.func_73869_a(GuiMEMonitorable.java:474) [GuiMEMonitorable.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_73869_a(GuiContainer.java) [bex.class:?]
	at codechicken.nei.guihook.GuiContainerManager.callKeyTyped(GuiContainerManager.java) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.keyTyped(GuiContainerManager.java:475) [GuiContainerManager.class:?]
	at codechicken.nei.guihook.GuiContainerManager.handleKeyboardInput(GuiContainerManager.java:465) [GuiContainerManager.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_146282_l(GuiContainer.java) [bex.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:276) [bdw.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

#### What happend instead? (Attach screenshots if needed)

#

**Comment by bartimaeusnek** [comment]
which version of Optifine do you use?

**Comment by lexx1191** [comment]
OptiFine_1.7.10_HD_U_E3 ,Previous versions GTNH of the builds worked fine

**Comment by Dream-Master** [comment]
Newer than D6 need fastcraft 1.25

**Comment by lexx1191** [comment]
is worth fastcraft 1.25

**Comment by Dream-Master** [comment]
fastcraft 1.23 have more preformance than 1.25 
I using Optifine D6 and Fastcraft 1.23 and i am fine

**Comment by lexx1191** [comment]
well, in the evening I will conduct the test

**Comment by Dream-Master** [comment]
ok let me know and close the issue when you think it is solved @lexx1191  thanks

**Comment by lexx1191** [comment]
spam remains, I will wait for the next version of the assembly, I close the question

**Comment by richardhendricks** [comment]
@lexx1191 Please retest with 2.0.4.5, I did a fix for Superbuffer lag.

**Comment by lexx1191** [comment]
[13:19:33] [Server thread/INFO]: [gregtech.api.metatileentity.BaseMetaTileEntity:func_145845_h:580]: WARNING: Possible Lag Source at [137, 44, -152] in Dimension 0 with 366193293ns caused by an instance of class gregtech.api.metatileentity.implementations.GT_MetaTileEntity_Hatch_Output
[13:21:17] [Server thread/WARN]: WARNING: Possible Lag Source at [137,40,-149] in Dimension 0 with 157766721 ns caused by an instance of class gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Cable
[13:21:41] [Server thread/INFO]: [gregtech.api.metatileentity.BaseMetaTileEntity:func_145845_h:580]: WARNING: Possible Lag Source at [292, 48, -347] in Dimension 0 with 284384191ns caused by an instance of class gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicBatteryBuffer
[13:22:17] [Server thread/INFO]: [gregtech.api.metatileentity.BaseMetaTileEntity:func_145845_h:580]: WARNING: Possible Lag Source at [133, 39, -162] in Dimension 0 with 106023996ns caused by an instance of class gtPlusPlus.xmod.gregtech.common.tileentities.storage.GT_MetaTileEntity_TieredTank
[13:23:02] [Client thread/WARN]: net.minecraft.entity.Entity.func_70109_d:1359
[13:23:02] [Client thread/WARN]: mcp.mobius.waila.api.impl.DataAccessorCommon.getNBTData:120


[13:29:06] [Server thread/WARN]: WARNING: Possible Lag Source at [257,51,-203] in Dimension 0 with 117833204 ns caused by an instance of class gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Cable
[13:30:09] [Client thread/INFO]: [CHAT] You can only sleep at night
[13:31:18] [Server thread/INFO]: [gregtech.api.metatileentity.BaseMetaTileEntity:func_145845_h:580]: WARNING: Possible Lag Source at [310, 53, -377] in Dimension 0 with 114385545ns caused by an instance of class gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicBatteryBuffer
[13:31:20] [Server thread/INFO]: [gregtech.api.metatileentity.BaseMetaTileEntity:func_145845_h:580]: WARNING: Possible Lag Source at [310, 51, -329] in Dimension 0 with 107781745ns caused by an instance of class gregtech.common.tileentities.automation.GT_MetaTileEntity_SuperBuffer
[13:32:22] [Server thread/INFO]: [gregtech.api.metatileentity.BaseMetaTileEntity:func_145845_h:580]: WARNING: Possible Lag Source at [133, 39, -168] in Dimension 0 with 353939608ns caused by an instance of class gtPlusPlus.xmod.gregtech.common.tileentities.storage.GT_MetaTileEntity_TieredTank


alas, still

**Comment by richardhendricks** [comment]
These look like your server is overloading in general.  Is it doing other operations?  The lag measurement is only the thread start/stop time.  If the CPU/OS swaps to a different thread/process during execution, that time is added to the time on the block. The TieredTank lag source, is it really just a tiered tank?  That to me says the server overall is overloaded, maybe doing virus scanning or other activities.

Please scan the reported blocks with the portable scanner.

Also, my comments on https://github.com/GTNewHorizons/NewHorizons/issues/3151 apply here - use a receiving output as small as possible since the super buffer has to compare every inventory slot against the receiving inventory slot.

**Comment by lexx1191** [comment]
i5 Haswell, 16 RAM, fps game jumps from 2 to 30, the game is allocated 3 cores, also running the Oracle to work, the problem with super buffers is, as small dust lag

on another computer, there is no optifine, and there is no Oracle, lag in the super buffer is present,
try superbuffer to be replaced by something else

**Comment by richardhendricks** [comment]
What does the superbuffer output into?  Just a packager? 

Can you use the hand scanner on the superbuffer and other lag sources listed?  I don't understand why a tiered tank would take 353939608ns (300+ms), except if the CPU is heavily loaded.  Same for output hatch at 366193293ns.

**Comment by richardhendricks** [comment]
Game FPS is not the same as ticks/second

Use /xu_tps to get a ticks per second report.  Look at the middle numbers.

**Comment by lexx1191** [comment]
https://imgur.com/a/jRg6SSu

**Comment by lexx1191** [comment]
https://imgur.com/a/HhdCo8F without optifine

**Comment by Dream-Master** [comment]
@lexx1191 autopackager lags to hell if you add it. We remove it because of lag and because gt have a way to do it too.

**Comment by lexx1191** [comment]
https://imgur.com/a/upqdG4g scanner superbuffer  tiny dust
https://imgur.com/a/Ao84zwy scanner superbuffer  small dust

**Comment by richardhendricks** [comment]
Please file new ticket if you are still having lag issues.

**Comment by lexx1191** [comment]
You can close the ticket, as a couple of days ago I started a new game, thanks.
