### ISSUE TITLE
What Java Ver for The update

### ISSUE THREAD

**Issue by Clowcadia** [GTNewHorizons/NewHorizons#3107]
#### Which modpack version are you using?
Latest
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
Installed 10, then 9 
#
#### What happend instead? (Attach screenshots if needed)
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	... 8 more
#

**Comment by bartimaeusnek** [comment]
use Java 8.

**Comment by vladisaev12** [comment]
> use Java 8. also this is an error that should be reported to MultiMC not here.

So, MultiMC/PrismLauncher don't work with Java 17+?
