### ISSUE TITLE
Killed Chaos Dragon - no credit for quest: #607

### ISSUE THREAD

**Issue by Highbeam** [GTNewHorizons/NewHorizons#3387]
#### Which modpack version are you using?
2.0.4.6
#

#### If in multiplayer; On which server does this happen? 
Epsilon
#

#### What did you try to do, and what did you expect to happen?
Killed Chaos Dragon
#

#### What happend instead? (Attach screenshots if needed)
Once I killed the Chaos Dragon, he began the death sequence and then I got dc'd from the server with a message 'Fatal error ****'.  This wasn't a client crash, just a server disconnect.

When I reconnected to the server, the chaos dragon was dead, there was no egg/dragon heart to be found and I had no credit for the quest (#607).  I was also dead from what I can assume were dark energy bolts that were still flying around.
#

#### What do you suggest instead/what changes do you propose?
Check the kill condition for the chaos dragon?

**Comment by Highbeam** [comment]
This is the message from the log:

[01:00:02] [Client thread/INFO]: [CHAT] You have just entered the wild
[01:00:02] [pool-4-thread-9/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@3c309f5[id=15c2f036-4749-4f7d-afec-b71607be3c98,name=Highbeem,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: The client has sent too many requests within a certain amount of time
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:65) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:135) [YggdrasilMinecraftSessionService.class:?]
	at net.minecraft.client.resources.SkinManager$3.run(SourceFile:106) [brm.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_161]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_161]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]

**Comment by Highbeam** [comment]
[2018-08-02-1.log.gz](https://github.com/GTNewHorizons/NewHorizons/files/2254198/2018-08-02-1.log.gz)

**Comment by Dream-Master** [comment]
kill task nothing is wrong. I guess the disconnect not count the death.

**Comment by Highbeam** [comment]
Just unlucky for me.  Please close this :) thanks
