### ISSUE TITLE
Crash - Fluid Registry Issues - 5.09.32.34

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/NewHorizons#3536]
Seems related to using addFluid() on a fluid generated using MaterialBuilder() instead of Material().  The .addFluid() already triggers it to be auto registered and the .addCell() does what you'd expect.

Possible Solutions:
1) Don't use MaterialBuilder
2) Use MaterialBuilder but don't have it auto register the fluid/cell, do it manually

```
[21:15:09] [Client thread/FATAL] [FML]: The fluid registry is corrupted. Something has inserted a fluid without registering it
[21:15:09] [Client thread/FATAL] [FML]: There is 4 unregistered fluids
[21:15:09] [Client thread/FATAL] [FML]:   Fluid name : saltwater, type: gregtech.api.objects.GT_Fluid
[21:15:09] [Client thread/FATAL] [FML]:   Fluid name : lifeessence, type: gregtech.api.objects.GT_Fluid
[21:15:09] [Client thread/FATAL] [FML]:   Fluid name : ethylene, type: gregtech.api.objects.GT_Fluid
[21:15:09] [Client thread/FATAL] [FML]:   Fluid name : ethane, type: gregtech.api.objects.GT_Fluid
```

```
java.lang.IllegalStateException: The fluid registry is corrupted
    at net.minecraftforge.fluids.FluidRegistry.getDefaultFluidName(FluidRegistry.java:297)
    at net.minecraftforge.fluids.FluidRegistry.writeDefaultFluidList(FluidRegistry.java:327)
    at net.minecraftforge.common.ForgeModContainer.getDataForWriting(ForgeModContainer.java:315)
    at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataSave(FMLCommonHandler.java:375)
    at net.minecraft.world.storage.SaveHandler.func_75761_a(SaveHandler.java:209)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2081)
```

```java
// Saltwater
public static Materials SaltWater = new MaterialBuilder(692, TextureSet.SET_FLUID, "Salt Water").addCell().addFluid().setRGB(0, 0, 200).setColor(Dyes.dyeBlue).constructMaterial();

// Newly added
 GT_Mod.gregtechproxy.addFluid("SaltWater", "Salt Water", Materials.SaltWater, 1, 295, GT_OreDictUnificator.get(OrePrefixes.cell, Materials.SaltWater, 1L), ItemList.Cell_Empty.get(1L, new Object[0]), 1000);


// Ethane
public static Materials Ethane                    = new MaterialBuilder(642, TextureSet.SET_FLUID      ,                                                                                                     "Ethane").addCell().addGas().setRGB(200, 200, 255).setColor(Dyes.dyeLightBlue).setFuelType(MaterialBuilder.GAS).setFuelPower(168).setMaterialList(new MaterialStack(Carbon, 2), new MaterialStack(Hydrogen, 6)).addElectrolyzerRecipe().setCanBeCracked(true).constructMaterial();

// Newly added
GT_Mod.gregtechproxy.addFluid("Ethane", "Ethane", Materials.Ethane, 2, 295, GT_OreDictUnificator.get(OrePrefixes.cell, Materials.Ethane, 1L), ItemList.Cell_Empty.get(1L, new Object[0]), 1000);
```

**Comment by Dream-Master** [comment]
what you suggest to add/remove? can you do a pull request @mitchej123 ?

**Comment by mitchej123** [comment]
Trying to track down @richardhendricks to find out what troubles he was having that caused him to add them in; once that's done I'll figure out a fix with him.

**Comment by Dream-Master** [comment]
ethylene had no gt cell so far I know

**Comment by richardhendricks** [comment]
I was just trying to get these fluids to the same state as Methane, since they would crash/error out the GT Scanner if I tried to add them to its hashmap. If you can find the "proper" way to use them in GT Scanner, that works fine by me.

**Comment by Dream-Master** [comment]
All works fine jsust tested.

https://cdn.discordapp.com/attachments/346762422754869248/484428935527137310/unknown.png
https://cdn.discordapp.com/attachments/346762422754869248/484429263366520834/unknown.png
