### ISSUE TITLE
Forestry Pollination Crash

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/NewHorizons#3713]
```
java.lang.NullPointerException: Unexpected error
	at forestry.arboriculture.items.ItemGermlingGE.func_77648_a(ItemGermlingGE.java:197)
	at net.minecraft.item.ItemStack.func_77943_a(Unknown Source)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by mitchej123** [comment]
Should be fixed here: https://github.com/GTNewHorizons/ForestryMC/commit/23c4e4ed91bcc9785c07ffd58103293ae62e8cf8
