### ISSUE TITLE
Genetics DataBank Issue

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#3913]
#### Which modpack version are you using?
2.0.6.0b
#
#### If in multiplayer; On which server does this happen? 
Private Server
#
#### What did you try to do, and what did you expect to happen?
Analyzed the bee and added it genes to DataBank of genetics.
#
#### What happend instead? (Attach screenshots if needed)
Not registered except for Species and Effect to DataBank and Error occurred.

Screenshots![2018-12-17_22 12 23](https://user-images.githubusercontent.com/40425798/50092932-acbaae00-0252-11e9-810f-d28722cacf3a.png)

Error Log
[22:24:41] [Server thread/WARN]: java.lang.NoSuchFieldException: mutationConditions
[22:24:41] [Server thread/WARN]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[22:24:41] [Server thread/WARN]: 	at gregtech.common.bees.GT_Bee_Mutation.getbasicChance(GT_Bee_Mutation.java:58)
[22:24:41] [Server thread/WARN]: 	at gregtech.common.bees.GT_Bee_Mutation.getChance(GT_Bee_Mutation.java:38)
[22:24:41] [Server thread/WARN]: 	at forestry.apiculture.genetics.Bee.mutateSpecies(Bee.java:648)
[22:24:41] [Server thread/WARN]: 	at forestry.apiculture.genetics.Bee.createOffspring(Bee.java:595)
[22:24:41] [Server thread/WARN]: 	at forestry.apiculture.genetics.Bee.spawnPrincess(Bee.java:548)
[22:24:41] [Server thread/WARN]: 	at forestry.apiculture.BeekeepingLogic.spawnOffspring(BeekeepingLogic.java:401)
[22:24:41] [Server thread/WARN]: 	at forestry.apiculture.BeekeepingLogic.killQueen(BeekeepingLogic.java:367)
[22:24:41] [Server thread/WARN]: 	at forestry.apiculture.BeekeepingLogic.canWork(BeekeepingLogic.java:188)
[22:24:41] [Server thread/WARN]: 	at forestry.apiculture.tiles.TileBeeHousingBase.updateServerSide(TileBeeHousingBase.java:121)
[22:24:41] [Server thread/WARN]: 	at forestry.core.tiles.TileForestry.func_145845_h(TileForestry.java:118)
[22:24:41] [Server thread/WARN]: 	at net.minecraft.world.World.func_72939_s(World.java:2583)
[22:24:41] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
[22:24:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
[22:24:41] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
[22:24:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
[22:24:41] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
[22:24:41] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by yukieiji** [comment]
Some Cultivated, Industrious, Ender

**Comment by Dream-Master** [comment]
ok but it shows an gt code error. the bees you named are from forestry I guess. @bartimaeusnek any idea?

**Comment by bartimaeusnek** [comment]
Have to looker deeper into the Genetics code, its some kind of incompability with the new GT bee layer that fixes the "less than 0.1%" mutation chanche

**Comment by Dream-Master** [comment]
@bartimaeusnek are you able to fix it?

**Comment by yukieiji** [comment]
It tested with ver 2.0.7.5, but this issue existed

**Comment by Dream-Master** [comment]
@Спартак 
the fix you posted is allready in GTNH GT code. Waht you mean ?

**Comment by Spartak1997** [comment]
@Dream-Master lol. Don't worry, I coped this PR.

**Comment by derek126** [comment]
Hmm any updates on this? I just spent the last day to two setting up a big genetics "lab". So, this is pretty frustrating.

**Comment by bartimaeusnek** [comment]
should be fixed with: https://github.com/GTNewHorizons/GT5-Unofficial/pull/205

**Comment by bartimaeusnek** [comment]
main ticket -> https://github.com/GTNewHorizons/NewHorizons/issues/4930
