### ISSUE TITLE
GT Teleporter crash the client when you try to tp into galacticraft dim

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/NewHorizons#4018]
#### Which modpack version are you using?
delta one
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
tried to tp into a dim using gt teleporter and i misclicked the dim id. Expected nothing to happen
#
#### What happend instead? (Attach screenshots if needed)
i crashed
here is the stacktrace:
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 1/23/19 8:14 PM
Description: Unexpected error

java.lang.IllegalArgumentException: Could not get provider type for dimension 28, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148)
	at net.minecraftforge.common.DimensionManager.createProviderFor(DimensionManager.java:302)
	at net.minecraft.world.WorldProvider.func_76570_a(WorldProvider.java:160)
	at net.minecraft.client.multiplayer.WorldClient.<init>(WorldClient.java:54)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(Unknown Source)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32)
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

tell me if you need the full crashreport
#
#### What do you suggest instead/what changes do you propose?
Please fix it.

**Comment by bartimaeusnek** [comment]
Its a Galacticraft bug, the dim is not invalid.

**Comment by boubou19** [comment]
i'm pretty sure the dim wasn't loaded. tomorrow i'll try it with a not existing dimension.
