### ISSUE TITLE
Malifica CTD Thaumcraft

### ISSUE THREAD

**Issue by Lithorn** [GTNewHorizons/NewHorizons#4079]
#### Which modpack version are you using?
2.0.6.7DEV
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Open Malifica Tab in thaum book
#
#### What happend instead? (Attach screenshots if needed)
Crashes to desktop each time
#
#### What do you suggest instead/what changes do you propose?
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at thaumcraft.client.gui.GuiResearchBrowser.genResearchBackground(GuiResearchBrowser.java:349)
    at thaumcraft.client.gui.GuiResearchBrowser.func_73863_a(GuiResearchBrowser.java:231)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Dream-Master** [comment]
From wich mod are the tab?

**Comment by Dream-Master** [comment]
@Lithorn

**Comment by Dream-Master** [comment]
fixed

**Comment by Lithorn** [comment]
Confirmed Fixed in 2.0.6.7C
