### ISSUE TITLE
Opis crash the Server

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#413]
every time when i try to using /opis the Server crash.

``````
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 12/1/15 6:39 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at mcp.mobius.opis.data.managers.TileEntityManager.getCumulativeAmountTileEntities(TileEntityManager.java:181)
	at mcp.mobius.opis.events.OpisServerTickHandler.tickEnd(OpisServerTickHandler.java:128)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_476_OpisServerTickHandler_tickEnd_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:264)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:797)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669)
	at java.lang.Thread.run(Thread.java:745)`
``````

**Comment by Namikon** [comment]
Try to update mobiusCore for KCauldron:
https://github.com/TCPR/Fixes/tree/master/KCauldron%20MobiusCore%20(Build%20157%2B)

If that doesn't help, there is little you can do; Except trying to open a bug report at ProfMobius's bugtracker

**Comment by Dream-Master** [comment]
Ok I will try it. Thanks

**Comment by Dream-Master** [comment]
Not crash any more.
