### ISSUE TITLE
crash when wearing Purification Talisman

### ISSUE THREAD

**Issue by secirpac** [GTNewHorizons/NewHorizons#419]
Maybe the mod itself (Warp Theory) is unstable.Will anyone do me a fevour?
The amulet is wearable,but minecraft will crash some time later.
here's the crash report.

---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 15-12-13 7:08 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at shukaro.warptheory.items.ItemAmulet.onWornTick(ItemAmulet.java:90)
	at baubles.common.event.EventHandlerEntity.playerTick(EventHandlerEntity.java:31)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_142_EventHandlerEntity_playerTick_LivingUpdateEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:287)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1560)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by Dream-Master** [comment]
http://jenkins.usrv.eu:8081/job/WarpTheory/

@secirpac can you test it please.

**Comment by secirpac** [comment]
I appreciate your help very much.I have already tested it.
the test last for two hours.

During the first hour of the test,i wore the talisman with no warp.It didn't crash as before.Nothing special has happened.

Next twenty minutes i set my warp to 20(Normal Warp),the number turned into 16 afer twenty minutes.a few warp events took place. 

In the last forty minutes,i set my warp to 100(Permanent Warp),the number turned into 94 after forty minutes.Number of the occurrence of warp events added up to 33(about).

I think the amulet was just working perfectly.Happily it's getting stable.
