### ISSUE TITLE
[Error] Could not pass event InventoryMoveItemEvent to WorldGuard v6.1

### ISSUE THREAD

**Issue by Dream-Master** [GTNewHorizons/NewHorizons#456]
The Server throw out this error every few seconds. This problem exist since yesterday.

@Namikon
Any Guess what kind of error this is ?`I look in google but cant fin any helpful.

``````
Caused by: java.lang.NullPointerException
[10:33:01] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to WorldGuard v6.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.tileentity.TileEntityHopper.func_145892_a(TileEntityHopper.java:561) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:490) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:251) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:231) [api.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2513) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
[10:33:04] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to WorldGuard v6.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.tileentity.TileEntityHopper.func_145892_a(TileEntityHopper.java:561) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:490) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:251) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:231) [api.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2513) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
[10:33:04] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to WorldGuard v6.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.UNOFFICIAL]
	at net.minecraft.tileentity.TileEntityHopper.func_145892_a(TileEntityHopper.java:561) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145891_a(TileEntityHopper.java:490) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:251) [api.class:?]
	at net.minecraft.tileentity.TileEntityHopper.func_145845_h(TileEntityHopper.java:231) [api.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2513) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:954) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException
``````

**Comment by Teteros** [comment]
>This problem exist since yesterday.

We started using Thaumatic Tinkerer's Essentia Funnel on hoppers then, maybe that doesn't play well with cauldron/worldguard?

**Comment by Dream-Master** [comment]
@Teteros 
switch it off please and we will see if the error still there.

**Comment by Dream-Master** [comment]
@Teteros 
The error is still there. so can you please disabled it to test it.

**Comment by Teteros** [comment]
Unfortunately that didn't seem to be it, with jars on hoppers removed.

**Comment by Dream-Master** [comment]
Error is gone.

**Comment by Namikon** [comment]
We will run into more of these problems as forge keeps updating. Most plugins for bukkit are not developed anymore (at least not for mc 1.7.10); So let's just hope it'll continue to work as long as possible

**Comment by Teteros** [comment]
Did this stop appearing since?
If so, then it may have been the essential funnel after all.

**Comment by Dream-Master** [comment]
Not seen any more.
