### ISSUE TITLE
Massive lag

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/NewHorizons#4713]
#### Which modpack version are you using?
2.0.7.5(added aromabackup, aroma1997core, ftbu, ftblib, optifine E7 and changed fastcraft to v1.25) 

I am having massive lag in singleplayer and I dont know why.
Its a new world, I am in stone age so there is no crazy laggy systems. 
I thought mining might be making the lag because it does more lag when mining.

**Comment by Impos913** [comment]
Maybe fastcraft and optifine is the problem. Its first time I am trying optifine in this pack and I wasnt having lag issues before.

**Comment by Impos913** [comment]
Removed optifine and changed fastcraft bavk to 1.23 and it seems to be fixed

**Comment by Dream-Master** [comment]
oh yes that don't worked for me too. Use fastcraft 1.23 and Optifine D6

**Comment by lexx1191** [comment]
_oh yes that don't worked for me too. Use fastcraft 1.23 and Optifine D6_

did not help, spam
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoSuchMethodError: gregtech.api.interfaces.metatileentity.IMetaTileEntity.getInventoryName()Ljava/lang/String;
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.setMetaTileEntity(BaseMetaTileEntity.java:1573)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at gregtech.api.metatileentity.MetaPipeEntity.setBaseMetaTileEntity(MetaPipeEntity.java:147)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.createNewMetatileEntity(BaseMetaTileEntity.java:243)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at gregtech.api.metatileentity.BaseMetaTileEntity.receiveMetaTileEntityData(BaseMetaTileEntity.java:610)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at gregtech.api.net.GT_Packet_TileEntity.process(GT_Packet_TileEntity.java:98)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at gregtech.common.GT_Network$HandlerShared.channelRead0(GT_Network.java:96)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at gregtech.common.GT_Network$HandlerShared.channelRead0(GT_Network.java:90)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:10:36] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

this block is constantly repeated
[latest.log](https://github.com/GTNewHorizons/NewHorizons/files/3301806/latest.log)

**Comment by bigbass1997** [comment]
I wasn't aware that it was even possible to have Optifine and fastcraft installed at the same time, without causing problems. Regardless, when you added Optifine, did you change any of the settings? If not, I don't think that would cause error messages, but it could cause a whole lot of performance issues.

Optifine is NOT a 'plug-n-play' mod. You should go through every setting, read the tooltips, and experiment to see what configuration works best for your own computer.

**Comment by lexx1191** [comment]
Alas, the removal optifine did not solve the problem, the spam log was attached
[latest.log](https://github.com/GTNewHorizons/NewHorizons/files/3302805/latest.log)

**Comment by Methes** [comment]
For me only Optifine U_D8 works with Fastcraft 1.25. The latest U_E7 version doesn't even start.

**Comment by Impos913** [comment]
@Dream-Master fastcraft 1.23 with optifine D6 worked fine, thanks
