### ISSUE TITLE
[GT++] Cannot change the mode on Large Processing Factory

### ISSUE THREAD

**Issue by 5lx** [GTNewHorizons/NewHorizons#4824]
#### Which modpack version are you using?
GTNH 2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
My private server
#
#### What did you try to do, and what did you expect to happen?
Using screwdriver right click on the control block on Large Processing Factory, it should change the mode to process different recipes.
#
#### What happened instead? (Attach screenshots if needed)
Kicked out from the server, and I got the following bug report from the server side:
```
java.lang.NullPointerException
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.resetRecipeMapForHatch(GregtechMeta_MultiBlockBase.java:1615) ~[GregtechMeta_MultiBlockBase.class:?]
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.resetRecipeMapForAllInputHatches(GregtechMeta_MultiBlockBase.java:1579) ~[GregtechMeta_MultiBlockBase.class:?]
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.resetRecipeMapForAllInputHatches(GregtechMeta_MultiBlockBase.java:1573) ~[GregtechMeta_MultiBlockBase.class:?]
	at gtPlusPlus.xmod.gregtech.api.metatileentity.implementations.base.GregtechMeta_MultiBlockBase.onScrewdriverRightClick(GregtechMeta_MultiBlockBase.java:1631) ~[GregtechMeta_MultiBlockBase.class:?]
	at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1318) ~[BaseMetaTileEntity.class:?]
	at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:307) ~[GT_Block_Machines.class:?]
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source) ~[mx.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556) ~[nh.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

The Industrial Material Press and Ore Washing Plant can change the mode, and works great.

#
#### What do you suggest instead/what changes do you propose?
Getting the large processing factory all modes working.

**Comment by Anarack** [comment]
Remove all fluid hatches before changing modes and you wont be kicked.

**Comment by 5lx** [comment]
Thanks @Anarack, the workaround works great.

**Comment by Dream-Master** [comment]
@5lx @Anarack can we close this ?

**Comment by Anarack** [comment]
Alk has not been able to work on it to the best of my knowledge.
Issue link for the gt++ side https://github.com/alkcorp/GTplusplus/issues/495

**Comment by Dream-Master** [comment]
ok
