### ISSUE TITLE
Kicked by server when performed inventory sort

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/NewHorizons#5350]
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
My Server
#
#### What did you try to do, and what did you expect to happen?
Performed an inventory sort.
#
#### What happened instead? (Attach screenshots if needed)
Kicked by server.
・Error logs
[19:38:54 WARN]: Failed to handle packet for /(my ip)
java.lang.ClassCastException: bq_standard.handlers.PlayerContainerListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:105) ~[aap.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:153) ~[aae.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
	at net.minecraft.inventory.Container.func_75144_a(Container.java:418) ~[zs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2075) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by yukieiji** [comment]
Again, I have tested this server on TickProfiler and this issues seems to occur.
[TickProfiler.jar](https://discordapp.com/channels/181078474394566657/401118216228831252/617097929991127061)

**Comment by mitchej123** [comment]
Need more details; how can we reproduce this?

What inventory are you sorting.  What's in the inventory.  How are you sorting the inventory?  You mention running tick profiler, does it say anything of note?

**Comment by mitchej123** [comment]
https://github.com/Funwayguy/BetterQuesting/issues/605

Based on this, I'm going to say it's a Thermos bug.

**Comment by mitchej123** [comment]
Which server is this? This server side mod claims to fix it: https://github.com/juanmuscaria/Gambiarra-BetterQuesting

**Comment by yukieiji** [comment]
Also kicked from server when inventory crafting.
So it seems to be a Thermos bug.....

My server is using Contigo-1.7.10-1614.UNOFFICIAL-server(Thermos fork)
[Contigo r59](https://github.com/djoveryde/Contigo/releases/tag/1.7.10-r59)

**Comment by mitchej123** [comment]
Yah, nothing we can do here.  Fix the thermos implementation, try that mod, or find another way to fix it.  We can't support Thermos/etc.

**Comment by yukieiji** [comment]
Ok, thank you @mitchej123.
