### ISSUE TITLE
Disconnect from Thermos server.

### ISSUE THREAD

**Issue by Pilad** [GTNewHorizons/NewHorizons#5437]
#### Which modpack version are you using?
2.0.8.3
#
#### What did you try to do, and what did you expect to happen?
Modpack is running on the Thermos(Thermos-1.7.10-1614-server) server. If you put wood or any item in the player’s inventory, then you are thrown from the server.
#
#### What happened instead? (Attach screenshots if needed)
In this case, the server console error and shutdown the player.

java.lang.ClassCastException: bq_standard.handlers.PlayerContainerListener cannot be cast to net.minecraft.entity.player.EntityPlayerMP
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:105) ~[aap.class:?]
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(InventoryCrafting.java:153) ~[aae.class:?]
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
	at net.minecraft.inventory.Container.func_75144_a(Container.java:418) ~[zs.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:2075) ~[nh.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[22:18:29] [Server thread/INFO]: Pilad lost connection: Internal server error
[22:18:29] [Server thread/INFO]: Pilad left the game.
#

**Comment by mitchej123** [comment]
Please search github issues before posting duplicates:
https://github.com/GTNewHorizons/NewHorizons/issues/5431
https://github.com/GTNewHorizons/NewHorizons/issues/5377
https://github.com/GTNewHorizons/NewHorizons/issues/5350

Also thermos is unsupported, run at your own risk.
