### ISSUE TITLE
client crash using Forestry worktable for GT components

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/NewHorizons#5486]
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
MP 
private
#
#### What did you try to do, and what did you expect to happen?
make HV motors in the table
#
#### What happened instead? (Attach screenshots if needed)
clint crashed
#
#### What do you suggest instead/what changes do you propose?
[crash-2020-01-31_21.22.17-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/4141289/crash-2020-01-31_21.22.17-client.txt)

**Comment by Dream-Master** [comment]
@mitchej123 any idea? is this a nei thig or another thing?

**Comment by mitchej123** [comment]
```
	at mods.battlegear2.recipies.CraftingHandeler.onCrafting(CraftingHandeler.java:20)
	at mods.battlegear2.BgPlayerTracker.onItemCrafted(BgPlayerTracker.java:31)
```

Looks battlegear2 related.

**Comment by mitchej123** [comment]
Well to be fair, bg2 is choking on a null item; unclear why it's getting a null item...

@botn365 Can you reliably reproduce this, or was it a one off crash?

**Comment by botn365** [comment]
it has happend 3 times
2 times on making HV conveyor  and 1 time on making the HV motor

**Comment by botn365** [comment]
but it happens on randome

**Comment by mitchej123** [comment]
@richardhendricks - This is happening in a forestry workbench, at all related to your changes?

```
Stacktrace:
	at mods.battlegear2.recipies.CraftingHandeler.onCrafting(CraftingHandeler.java:20)
	at mods.battlegear2.BgPlayerTracker.onItemCrafted(BgPlayerTracker.java:31)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_69_BgPlayerTracker_onItemCrafted_ItemCraftedEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.firePlayerCraftingEvent(FMLCommonHandler.java:570)
	at forestry.core.gui.slots.SlotCrafter.func_82870_a(SlotCrafter.java:63)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:238)
	at forestry.core.gui.ContainerForestry.func_75144_a(ContainerForestry.java:82)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(Unknown Source)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:513)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:456)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:394)
	at forestry.core.gui.GuiForestry.func_73864_a(GuiForestry.java:146)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
```

**Comment by richardhendricks** [comment]
Does the modified title reflect the situation?  Only GT components are causing this issue?

**Comment by mitchej123** [comment]
My best guess is the size is somehow less than zero, and the itemStack is getting nulled out.  Pushed a patch @ https://github.com/GTNewHorizons/Battlegear2/commit/80c6e28927caf6ab8c768122513a707276899db6 but still not 100% clear as to _why_ it's happening or what else will blow up

**Comment by Dream-Master** [comment]
i upload a new version if somone want to test
@botn365 
https://github.com/GTNewHorizons/Battlegear2/releases/tag/1.0.8.5
