### ISSUE TITLE
HoloInventory glasses crash

### ISSUE THREAD

**Issue by mitchej123** [GTNewHorizons/NewHorizons#5752]
GTNewHorizonsServer-1.7.10-2.0.8.7.dev.QF2.zip

 holoinventory{2.0.0-beta2-GTNH} [Holo Inventory] (holoinventory-1.7.10-2.0.0-beta2-GTNH.jar)

```
19 java.lang.NoClassDefFoundError: net/minecraft/client/multiplayer/WorldClient
 20         at net.dries007.holoInventory.items.HoloGlasses.onEquipped(HoloGlasses.java:87) ~[HoloGlasses.class:?]
 21         at baubles.common.container.InventoryBaubles.func_70299_a(InventoryBaubles.java:146) ~[InventoryBaubles.class:?]
 22         at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77) ~[aay.class:?]
 23         at cofh.lib.util.helpers.InventoryHelper.mergeItemStack(InventoryHelper.java:360) ~[InventoryHelper.class:?]
 24         at net.minecraft.inventory.Container.func_75135_a(SourceFile) ~[zs.class:?]
 25         at baubles.common.container.ContainerPlayerExpanded.func_82846_b(ContainerPlayerExpanded.java:194) ~[ContainerPlayerExpanded.class:?]
 26         at net.minecraft.inventory.Container.func_75144_a(SourceFile:193) ~[zs.class:?]
 27         at net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883) ~[nh.class:?]
 28         at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
 29         at net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
 30         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
 31         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
 32         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
 33         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
 34         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
 35         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
 36         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
 37 Caused by: java.lang.ClassNotFoundException: net.minecraft.client.multiplayer.WorldClient
 38         at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
 39         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
 40         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
 41         ... 17 more
 42 Caused by: java.lang.RuntimeException: Attempted to load class bjf for invalid side SERVER
 43         at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:50) ~[forge-1.7.10-10.13.4.1614-1.7.10-universal.jar:?]
 44         at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
 45         at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
 46         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_201]
 47         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_201]
 48         ... 17 more
```

**Comment by seitenca** [comment]
try the new version https://github.com/GTNewHorizons/HoloInventory/releases/tag/2.1.0-beta

**Comment by seitenca** [comment]
@mitchej123 It crash only servers?

**Comment by mitchej123** [comment]
Only the server crashed, the client didn't.

**Comment by mitchej123** [comment]
I haven't tried the newest download yet -- I just rolled back to an earlier version of holoinventory and I'm playing with that right now.

**Comment by seitenca** [comment]
I think it is solved because  @Zoko061602  has change a lot of things

**Comment by seitenca** [comment]
@Zoko061602 someone say that the lastest version also crash on server

**Comment by wlhlm** [comment]
@Dream-Master can we get the log from Zeta? Crash was around 13:35 CET.

**Comment by seitenca** [comment]
the new version works on server

**Comment by seitenca** [comment]
maybe we need to do a QF to add the new version

**Comment by Hyperic88** [comment]
When moved that holo glasses into inventory - server crashed... Zeta

**Comment by seitenca** [comment]
@Hyperic88 with the lastest version in the server and client?

**Comment by Houstonruss** [comment]
Can confirm this crashes server 8.7

**Comment by ShinyHobo** [comment]
The server will also crash if you try to remove them after restarting the server. You have to delete the player.baub file for the affected player in order to get rid of them.

**Comment by Dream-Master** [comment]
@ShinyHobo @Houstonruss  try this one
https://github.com/GTNewHorizons/HoloInventory/releases/tag/2.1.3-beta
