### ISSUE TITLE
 Draconic Evolution and Battlegear2: client crash

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#750]
How to reproduce:

<del>- wear backpack, put tool into tool slot;</del>
- go to battle stance (press R);
- try to change instrument (Shift + WheelUp / WheelDown).

```
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 113
    at net.minecraft.entity.player.InventoryPlayer.func_70301_a(InventoryPlayer.java:577)
    at mods.battlegear2.api.core.InventoryPlayerBattle.func_70301_a(InventoryPlayerBattle.java:395)
    at com.brandon3055.draconicevolution.client.keybinding.KeyInputHandler.onMouseInput(KeyInputHandler.java:98)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_1266_KeyInputHandler_onMouseInput_MouseInputEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at cpw.mods.fml.common.FMLCommonHandler.fireMouseInput(FMLCommonHandler.java:535)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1735)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
```

**Comment by Dream-Master** [comment]
@Ugachaga Ok reported to the Mod Dev too. 
Did this happened with any launcher. I see you are using Multi MC did you try with Technic or FTB too ?

**Comment by Ugachaga** [comment]
Tested on FTB fresh install with same result. 
However, no crash if Draconic Evolution disabled.

**Comment by Ugachaga** [comment]
Well, tested this a bit deeply. Minecraft with only Forge, Draconic Evolution and Battlegear2.

1. Go to battle stance.
2. Select 3rd Battlegear slot.
3. Press Shift+WheelDown -> 100% Crash.

WheeUp, Shift+WheeUp, WheeDown - works good. 
Change slot 1 to 2 or 2 to 3 by Shift+WheelDown - works good.
And only сhange slot 3 to 1 by Shift+WheelDown crashed the game.

**Comment by Dream-Master** [comment]
Thanks for detailed testings. Not sure we can do anything against it. DE Code is open source but i am  not sure if Mine and Blade source is.

**Comment by Ugachaga** [comment]
https://youtu.be/VzpbOXJYHxU?t=13m25s

**Comment by Ugachaga** [comment]
GTNH 1.2.0.0pre includes old Draconic-Evolution-1.7.10-1.0.2i.jar so issue is still here

**Comment by Dream-Master** [comment]
The version "i" is the last source available on DE repro plus the code we add to De. So far I know there is no newer source available for 1.7.10. I just use the version in 1.1.x.x too.

**Comment by Dream-Master** [comment]
@Ugachaga Did you have a never version that works?
I update the pack to 1.2.0.0 pre was only a test build but i not change DE mod.

**Comment by Ugachaga** [comment]
http://jenkins.usrv.de:8081/job/Draconic-Evolution/ version "**j**" is the last on your Jenkins. It include fix I offered and works good.

**Comment by Dream-Master** [comment]
@Ugachaga Thanks . Will upload a quickfix this evening.

**Comment by Ugachaga** [comment]
Could you also update [BackpackMod](https://github.com/runescapejon/Minecraft-Backpack-Mod/releases) to 2.2.3 It disallow backpacks in backpacks like adventurebackpack do.

**Comment by Dream-Master** [comment]
Sure
