### ISSUE TITLE
Naming Healing axe crashes game

### ISSUE THREAD

**Issue by rijodan** [GTNewHorizons/NewHorizons#854]
tried naming my healing axe and crashed my game heres crash log
[crash-2016-12-01_16.02.37-client.txt](https://github.com/GTNewHorizons/NewHorizons/files/625852/crash-2016-12-01_16.02.37-client.txt)

**Comment by Dream-Master** [comment]
I guess nothing we can do here i guess.
@Technus or we able to fix this?

**Comment by Technus** [comment]
well my healing axe i named so some update broke it

**Comment by Dream-Master** [comment]
we not updating tinkers contruct for ages. Any idea which mod does it?

**Comment by Technus** [comment]
it has nothing to do with TICO

**Comment by Technus** [comment]
Healing axe is not tico.

**Comment by Dream-Master** [comment]
Ok but Extra Utilies nerver get an update for more then 1 year.

**Comment by Dream-Master** [comment]
But tico is in the stack trace.

**Comment by Dream-Master** [comment]
at tconstruct.tools.logic.ToolStationLogic.canRename(ToolStationLogic.java:216)
	at tconstruct.tools.inventory.ToolForgeContainer.craftTool(ToolForgeContainer.java:103)
	at tconstruct.tools.inventory.ToolStationContainer.mergeCraftedStack(ToolStationContainer.java:202)
	at tconstruct.tools.inventory.ToolStationContainer.func_82846_b(ToolStationContainer.java:109)

**Comment by Technus** [comment]
use anvil to rename healing axe not tico table
