### ISSUE TITLE
Log spam filling up hard drive space

### ISSUE THREAD

**Issue by adamcirillo** [GTNewHorizons/NewHorizons#875]
I just updated my gtnh server to 1.2.1.0 and the gregtech.log fills up the hard drive space in like 10 minutes and spams this non stop 

java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityClientPlayerMP
	at gregtech.api.metatileentity.implementations.GT_MetaPipeEntity_Fluid.onPostTick(GT_MetaPipeEntity_Fluid.java:271)
	at gregtech.api.metatileentity.BaseMetaPipeEntity.func_145845_h(BaseMetaPipeEntity.java:259)
	at net.minecraft.world.World.func_72939_s(World.java:2583)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:673)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:986)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityClientPlayerMP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 9 more

never had issues using 1.2.0.0 server files were both from the technic website download link

**Comment by bigbass1997** [comment]
This issue has been fixed in the dev versions. Until the next modpack update, all you need to do is download the following jar files and update them on the server:

http://jenkins.usrv.de:8081/job/Gregtech-5-Unofficial/264/
http://jenkins.usrv.de:8081/job/GTNewHorizons-Core-Mod/135/

The jars go in the mods folder, be sure to replace the originals.

This fix only needs to be done on the server side, not the client.

**Comment by adamcirillo** [comment]
You can close the issue now its fixed for me

**Comment by Dream-Master** [comment]
Open untill i release a new update.
