### ISSUE TITLE
Gadomancy eldirtch portal is broken (low priority)

### ISSUE THREAD

**Issue by Mylezz** [GTNewHorizons/NewHorizons#877]
The gadomancy elders portal does not teleport you when you walk in it.
Also in single player doesn't work,
When i download the mod in a clean pack it works fine.
So its a pack bug.

This is a (low priority issue) just an annoying one..

**Comment by Dream-Master** [comment]
Clean pack? I know it not works in GTNH but I don't know why.

**Comment by Mylezz** [comment]
Fresh forge install vanilla, is a clean install

**Comment by KaneHart** [comment]
Could this be a issue with the missing configs?

**Comment by Mylezz** [comment]
Yea could be

**Comment by KaneHart** [comment]
Here is the server side config it might help out:
http://pastebin.com/sPD7HTUm

**Comment by Mylezz** [comment]
dose it work on ur server?

**Comment by Dream-Master** [comment]
It's a creative portal so far I know so a nice to have but not necessary thing.

**Comment by Drobac** [comment]
Ill make one and test later today

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21590097/f7d5081e-d0f8-11e6-9ae3-f240b09696a1.png)
For me it worked. It is a Creative item only so i close this now.

**Comment by Dream-Master** [comment]
I guess it is the Portal of the Voidwalker @KaneHart , @Mylezz @Drobac ?

**Comment by HellFirePvP** [comment]
Be sure to only open a portal in the overworld. Other dimensions might not work.

**Comment by Dream-Master** [comment]
````
[14:52:04] [GadomancyEldritchGen (SERVER/ThreadID=5438)/WARN]: Exception in thread "GadomancyEldritchGen (SERVER/ThreadID=5438)" 
[14:52:04] [GadomancyEldritchGen (SERVER/ThreadID=5438)/WARN]: java.lang.NullPointerException
[14:52:04] [GadomancyEldritchGen (SERVER/ThreadID=5438)/WARN]: 	at net.minecraft.world.World.getChunkIfLoaded(World.java:4931)
[14:52:04] [GadomancyEldritchGen (SERVER/ThreadID=5438)/WARN]: 	at net.minecraft.world.World.func_147463_c(World.java:4940)
[14:52:04] [GadomancyEldritchGen (SERVER/ThreadID=5438)/WARN]: 	at makeo.gadomancy.common.utils.world.TCMazeHandler$MazeBuilderThread.run(TCMazeHandler.java:273)
````
Server log
