### ISSUE TITLE
Bits 1.3.0.0pre

### ISSUE THREAD

**Issue by Ugachaga** [GTNewHorizons/NewHorizons#995]
- Lootbags "Magic Grandmaster - Unique" sometimes do not give any item and sometimes it freeze server completly, only hard restart helps. Seems something wrong with loottables. Same problem was with "Legendary - Unique" on 1.2.0.1. Tested on Fortune versions.
Btw, low-tier bags has unattainable expensive recipe to Fortune version. Like "LootBag (Basic)" required clay (it's ok) and Fortune III book (noway to get it on this level and no reason to spend on higher levels). Not sure if issue.
- Reminder: Bat (nightvision) and Iron Golem (eliminate fall damage) backpacks has no recipes.
- Is it by design what Draconium ore can be found in Twilight Forest?

**Comment by Dream-Master** [comment]
Ok will check the lootbags.
Any suggestions with the fortune recipe. I guess on lv you not using any Fortune bags. And if it get fortune 3 it needs at least a furtune 3 book. 
Yes i need to make some recipe for it after i disable the packs.
Draconium in TF mh need to check but normaly only in the end and later game planets.

**Comment by Dream-Master** [comment]
`` # Set to true to prevent draconium ore from spawning in the end
    B:"Disable Ore Spawn (End)"=false

    # Set to true to prevent draconium ore from spawning in the nether
    B:"Disable Ore Spawn (Nether)"=true

    # Set to true to prevent draconium ore from spawning in the overworld
    B:"Disable Ore Spawn (Overworld)"=true``

**Comment by Dream-Master** [comment]
Gregtech cfg are right so no error seen. Not sure why you have Draconium ore in TF.

**Comment by Ugachaga** [comment]
1.3.0.0pre1 clean install, new worl generated, 
/cofh clearblocks _your_name_ 100 100 100 *fluid stone dirt grass sand gravel cobblestone *tree *plant ice
![draconiumtf](https://cloud.githubusercontent.com/assets/19178671/21958962/47e34094-daec-11e6-8172-db6578932c53.png)
It's definetely not GT, just a few pieces here and there.

**Comment by Drobac** [comment]
Draconium can't be processed pre LuV so even if you find the vanilla spawn, it won't help much

**Comment by Dream-Master** [comment]
will look into it but gt worlgen says me that it is disabled. Will  check tomorrow.

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21962115/cd60d64c-db1d-11e6-9aae-19aacf205c77.png)
![image](https://cloud.githubusercontent.com/assets/2970688/21962116/d0edf34e-db1d-11e6-80ed-a17c880e5e39.png)
![image](https://cloud.githubusercontent.com/assets/2970688/21962117/d40bb7b4-db1d-11e6-9d6e-d6d132a99c91.png)
![image](https://cloud.githubusercontent.com/assets/2970688/21962118/d777f82c-db1d-11e6-94f6-abc6dbfc12f5.png)

**Comment by Dream-Master** [comment]
![image](https://cloud.githubusercontent.com/assets/2970688/21962119/f7157a74-db1d-11e6-876b-98fdf8c0954a.png)
![image](https://cloud.githubusercontent.com/assets/2970688/21962122/fcbbdbb2-db1d-11e6-8299-9aa252b2c895.png)

**Comment by Dream-Master** [comment]
I open 64 Grandmaster Lootbags and 2 have nothing. Will set loot wight a bit higher.

**Comment by Ugachaga** [comment]
Grandmaster Unique or just Grandmaster? Regular Grandmaster works fine.

**Comment by Dream-Master** [comment]
Unique bugs.

``[12:32:33] [Server thread/ERROR] [ENHANCEDLOOTBAGS/]: Unable to spawn dropitem in world
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at eu.usrv.enhancedlootbags.core.items.ItemLootBag.func_77659_a(ItemLootBag.java:172)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.item.ItemStack.func_77957_a(Unknown Source)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.management.ItemInWorldManager.func_73085_a(Unknown Source)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:539)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.at.a(F:978)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at fastcraft.H.aq(F:36)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
[12:32:33] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)``

**Comment by Ugachaga** [comment]
Yeah, got this log warning also. But the worst that it freeze server as a result.

**Comment by Dream-Master** [comment]
my Game crashing too. I ask Namikon the Mod dev and he said maybe some item are wrong. I need to check that.

**Comment by Technus** [comment]
@Namikon - to fix the lootbags

**Comment by Dream-Master** [comment]
@Technus relax he is informed allready ;)

**Comment by kokochicken** [comment]
@drobac you can alloy smelt draconium cells at lv

**Comment by Drobac** [comment]
Fixed with the update already

**Comment by Technus** [comment]
@Dream-Master ik but just updating the status of the issue.

**Comment by Ugachaga** [comment]
Lootbags 1.0.2, Grandmaster - Unique, after 1st failing to create item and string "try again" bag bugged and say "try again"everytime:
![tryagain](https://cloud.githubusercontent.com/assets/19178671/21982901/09cd9fbc-dc21-11e6-8796-a16cc94ac3d3.png)

```
[Server thread/ERROR]: Skipping loot TaintedMagic:PrimalBlade; Unable to get ItemStack. Make sure this item exists!
[Server thread/ERROR]: Skipping loot TaintedMagic:FocusTime; Unable to get ItemStack. Make sure this item exists!
```
Also in [lang](https://github.com/GTNewHorizons/EnhancedLootBags/blob/b0845b8bdd84f278bbe90cf91c5eee70adcb8618/src/main/resources/assets/enhancedlootbags/lang/en_US.lang#L3) missing ".string" so message is unlocalized.

**Comment by Dream-Master** [comment]
@Ugachaga Ok the Tainted magic items need to be changed because of new version.
@Namikon Can you add the message in the lang file.
